### ISSUE TITLE
Counter serialization broken

### ISSUE THREAD

**Issue by enoriega** [clulab/processors#104]
When calling `Counter.saveTo(w:Writter)` the contents of the object are not saved to the stream. I tried replacing a `FileWriter` with a `StringWriter` for debugging and it just remains empty after calling the saveTo method. Neither flushing the stream or closing it after the write helps. There is no exception thrown, just nothing happens.

**Comment by MihaiSurdeanu** [comment]
@enoriega: looks like a bug. I'll take a look.

**Comment by MihaiSurdeanu** [comment]
@enoriega: see https://github.com/clulab/processors/blob/master/main/src/test/scala/org/clulab/struct/TestCounter.scala 
for an example for proper serialization using saveTo.

**Comment by MihaiSurdeanu** [comment]
to be clear: it's not a bug. just weird Java writers...
