### ISSUE TITLE
Build failing with mvn

### ISSUE THREAD

**Issue by lucasnoah** [clulab/processors#11]
Hi
Every time I try and build the .jar files with mvn package it fails.  I am including my full -e output below.   

Thanks

[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for edu.arizona.sista:processors:jar:2.0
[WARNING] 'build.plugins.plugin.version' for org.scala-tools:maven-scala-plugin is missing. @ line 89, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building processors 2.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ processors ---
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ processors ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 42 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ processors ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-scala-plugin:2.15.2:compile (default) @ processors ---
[INFO] Checking for multiple versions of scala
[WARNING]  Expected all dependencies to require Scala version: 2.10.1
[WARNING]  edu.arizona.sista:processors:2.0 requires scala version: 2.10.1
[WARNING]  org.scalatest:scalatest_2.10:2.0.M6-SNAP17 requires scala version: 2.10.0
[WARNING] Multiple versions of scala libraries detected!
[INFO] includes = [**/*.scala,**/*.java,]
[INFO] excludes = []
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.5:testResources (default-testResources) @ processors ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /var/opt/ENV/lib/processors/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ processors ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-scala-plugin:2.15.2:testCompile (default) @ processors ---
[INFO] Checking for multiple versions of scala
[WARNING]  Expected all dependencies to require Scala version: 2.10.1
[WARNING]  edu.arizona.sista:processors:2.0 requires scala version: 2.10.1
[WARNING]  org.scalatest:scalatest_2.10:2.0.M6-SNAP17 requires scala version: 2.10.0
[WARNING] Multiple versions of scala libraries detected!
[INFO] includes = [**/*.scala,**/*.java,]
[INFO] excludes = []
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.6:test (default-test) @ processors ---
[INFO] Surefire report directory: /var/opt/ENV/lib/processors/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running edu.arizona.sista.processors.TestFastNLPProcessor
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.302 sec <<< FAILURE!
Running edu.arizona.sista.processors.TestProcessorThreading
Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.07 sec <<< FAILURE!
Running edu.arizona.sista.processors.TestCoreNLPProcessor
Adding annotator tokenize
Adding annotator ssplit
Adding annotator tokenize
Adding annotator tokenize
Adding annotator ssplit
Adding annotator pos
Reading POS tagger model from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [3.2 sec].
Adding annotator tokenize
Adding annotator pos
Adding annotator lemma
Adding annotator tokenize
Adding annotator pos
Adding annotator lemma
Adding annotator ner
Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [7.8 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [7.6 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [5.4 sec].
Initializing JollyDayHoliday for sutime
Reading TokensRegex rules from edu/stanford/nlp/models/sutime/defs.sutime.txt
Reading TokensRegex rules from edu/stanford/nlp/models/sutime/english.sutime.txt
Mar 02, 2014 12:15:49 PM edu.stanford.nlp.ling.tokensregex.CoreMapExpressionExtractor appendRules
INFO: Ignoring inactive rule: temporal-composite-8:ranges
Reading TokensRegex rules from edu/stanford/nlp/models/sutime/english.holidays.sutime.txt
Adding annotator tokenize
Adding annotator parse
Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [1.9 sec].
Constituent parse tree: 
(ROOT
    (S
        (NP
            (NNP John)
            (NNP Doe)
        )
        (VP
            (VBD went)
            (PP
                (TO to)
                (NP
                    (NNP China)
                )
            )
        )
    )
)
Adding annotator tokenize
Adding annotator ssplit
Adding annotator pos
Adding annotator lemma
Adding annotator ner
Adding annotator parse
Adding annotator dcoref
Adding annotator tokenize
Adding annotator parse
List(
(NP
    (NNP John)
    (NNP Doe)
), 
(NP
    (DT the)
    (NN president)
), 
(NP
    (NNP IBM)
), 
(NP
    (NNP China)
))
Adding annotator tokenize
Adding annotator parse
S constituent is: 
(S
    (NP
        (NNP John)
        (NNP Doe)
    )
    (VP
        (VBD went)
        (PP
            (TO to)
            (NP
                (NNP China)
            )
        )
    )
)
NP constituent is: 
(NP
    (NNP John)
    (NNP Doe)
)
VP constituent is: 
(VP
    (VBD went)
    (PP
        (TO to)
        (NP
            (NNP China)
        )
    )
)
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 84.053 sec
Running edu.arizona.sista.processors.TestDocumentSerializer
Adding annotator tokenize
Adding annotator ssplit
Adding annotator pos
Adding annotator lemma
Adding annotator ner
Adding annotator parse
Adding annotator dcoref
Constructed a document with 2 sentences.
Generated annotations:
S	2
T	6
John	0	4	NNP	John	PERSON	O	_
Doe	5	8	NNP	Doe	PERSON	O	_
went	9	13	VBD	go	O	O	_
to	14	16	TO	to	O	O	_
China	17	22	NNP	China	LOCATION	O	_
.	22	23	.	.	O	O	_
D	1
2
1	0	nn
2	1	nsubj
2	4	prep_to
EOX
Y	1
ROOT	0	0	6	1	S	1	0	6	3	NP	1	0	2	2	NNP	0	0	1	1	John	0	0	1	0	NNP	0	1	2	1	Doe	0	1	2	0	VP	0	2	5	2	VBD	0	2	3	1	went	0	2	3	0	PP	0	3	5	2	TO	0	3	4	1	to	0	3	4	0	NP	0	4	5	1	NNP	0	4	5	1	China	0	4	5	0	.0	5	6	1	.	0	5	6	0
EOS
T	6
There	24	29	RB	there	O	O	_
,	29	30	,	,	O	O	_
he	31	33	PRP	he	O	O	_
visited	34	41	VBD	visit	O	O	_
Beijing	42	49	NNP	Beijing	LOCATION	O	_
.	49	50	.	.	O	O	_
D	1
3
3	0	advmod
3	2	nsubj
3	4	dobj
EOX
Y	1
ROOT	0	0	6	1	S	3	0	6	5	ADVP	0	0	1	1	RB	0	0	1	1	There	0	0	1	0	,	0	1	2	1	,0	1	2	0	NP	0	2	3	1	PRP	02	3	1	he	0	2	3	0	VP	0	35	2	VBD	0	3	4	1	visited	0	3	40	NP	0	4	5	1	NNP	0	4	5	1Beijing	0	4	5	0	.	0	5	6	1	.0	5	6	0
EOS
C	4
0	1	0	2	1
1	4	4	5	3
1	2	2	3	1
0	4	4	5	2
EOD

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.368 sec

Results :

Tests in error: 
  testParser2(edu.arizona.sista.processors.TestFastNLPProcessor)
  testParser1(edu.arizona.sista.processors.TestFastNLPProcessor)
  testTwoThreadsSameProcCoreNLP(edu.arizona.sista.processors.TestProcessorThreading)
  testTwoThreadsDifferentProcCoreNLP(edu.arizona.sista.processors.TestProcessorThreading)
  testTwoThreadsSameProcFastNLP(edu.arizona.sista.processors.TestProcessorThreading)
  testTwoThreadsDifferentProcFastNLP(edu.arizona.sista.processors.TestProcessorThreading)

Tests run: 17, Failures: 0, Errors: 6, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:30.794s
[INFO] Finished at: Sun Mar 02 12:16:45 PST 2014
[INFO] Final Memory: 11M/210M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.6:test (default-test) on project processors: There are test failures.
[ERROR] 
[ERROR] Please refer to /var/opt/ENV/lib/processors/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.6:test (default-test) on project processors: There are test failures.

Please refer to /var/opt/ENV/lib/processors/target/surefire-reports for the individual test results.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to /var/opt/ENV/lib/processors/target/surefire-reports for the individual test results.
	at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:55)
	at org.apache.maven.plugin.surefire.SurefirePlugin.execute(SurefirePlugin.java:592)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by MihaiSurdeanu** [comment]
Was this fixed? Closing for now. We can re-open if needed.
