### ISSUE TITLE
Implement Akka client/server for CoreNLP processors

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/processors#110]

**Comment by Matthalp** [comment]
If you are okay with using Play (https://www.playframework.com/) instead of Akka directly, I would be willing to contribute a skeleton project. I also have *modest* support for a RESTFUL Brat endpoint that could be included

**Comment by MihaiSurdeanu** [comment]
Thanks! But we'd prefer to work directly with Akka to minimize external dependencies.
On another note, play *is* cool.

**Comment by Matthalp** [comment]
I know all of you have a lot on your plate already, so if I get some time over winter break I can look into creating a RESTful skeleton project to serve as a reference and what not

**Comment by MihaiSurdeanu** [comment]
Sounds good. Thanks!

**Comment by hickst** [comment]
Finally...implemented in Processors release 6.0.7 and Reach release 1.3.4.
