### ISSUE TITLE
Enhance NER to load multiple override files

### ISSUE THREAD

**Issue by hickst** [clulab/processors#124]
I've generated a KB file (Phase3-Override.tsv.gz) for the proteins specified by MITRE for Phase3. It contains almost 700 entries, some of which probably conflict with our existing KBs and NER override file.

While we could add all these entries to the front of the existing NER override file (more than doubling its size), it would be better if Reach could handle multiple override files. The Grounding package can already handle this (reading the list of override files from the application.conf file) but the NER needs to be enhanced to load and process multiple override KBs (preferably from a configuration list).

This would also be extremely valuable for "one-off" processing requests from various groups who wish to use their own, custom groundings which override our default mappings.

**Comment by MihaiSurdeanu** [comment]
@hickst: can you please implement this?

We need to modify the `loadAll` method in KBLoader:
https://github.com/clulab/processors/blob/master/corenlp/src/main/scala/org/clulab/processors/bionlp/ner/KBLoader.scala

**Comment by hickst** [comment]
This is implemented and passes Processor tests on my machine but runs out of memory on Travis.

**Comment by MihaiSurdeanu** [comment]
Ok. Then I propose to merge and release processors.
We will have to run some experiments for CMU in the next couple of days for the next DARPA eval. So we should have this available.

**Comment by hickst** [comment]
I'm retesting with latest right now, just to be sure.

**Comment by hickst** [comment]
Tests pass again BUT let's hold off on merge and release until we discuss -- there are other issues which may need to go into a new release.

**Comment by hickst** [comment]
Code was merged by pull request #129
