### ISSUE TITLE
Minor tweaks to README for newbies

### ISSUE THREAD

**Issue by maxdh** [clulab/processors#126]
I just started out with Scala today in order to be able to use your code. As an absolute beginner a couple of things were not immediately obvious to me from the **Annotating entire documents** sample, such as which import statements were required. From my limited understanding I think they are the following:
```
import org.clulab.processors.Processor
import org.clulab.processors.corenlp.CoreNLPProcessor
import org.clulab.struct.DirectedGraphEdgeIterator
```
 Also I believe in the line `val proc:Processor = new CoreNLPProcessor(withDiscourse = true)`, `withDiscourse` actually requires an int now rather than a Boolean. 
These are just minor points which may help others in a similar position. Thank you!

**Comment by MihaiSurdeanu** [comment]
I believed I fixed all these issues. Please let me know if you see anything else!
Keep up the Scala coding!
