### ISSUE TITLE
NullPointerExcepton

### ISSUE THREAD

**Issue by wangxiangtao** [clulab/processors#13]
Hi ,I run the testParser1 method in TestFastNLPProcessor .
it throw NullPointerExcepton for the below lines:

// sista: it is possible that model files are included in a jar with a different name
        // (this happens in the jar distribution of processors)
        // inspect all jars in the classpath, to see if any contains our model files
        if(! found) {
          String infoFile = getName() + File.separator + getName() + "_singlemalt.info";
          InputStreamReader inputReader = new InputStreamReader(this.getClass().getClassLoader().getResourceAsStream(infoFile));

i guess it did not import the model file .  but i already import processors-2.1.jar and And I import the processors-2.1-model.jar also.  I donot know where the issue ?   (I have tested the corenlpTest , it is ok)

**Comment by myedibleenso** [comment]
Haven't heard anything on this since Jun 11, 2014.  I'm going to close this, but we can always reopen if needed...
