### ISSUE TITLE
invalid tap names for svmlight and svmrank

### ISSUE THREAD

**Issue by polymorpher** [clulab/processors#145]
'myedibleenso/nlp/svmrank' and 'myedibleenso/nlp/svmlight' are not available for tapping on brew. Can you update the README file?

**Comment by myedibleenso** [comment]
@polymorpher, does `brew tap myedibleenso/nlp` followed by `brew install svmlight svmrank` work for you?

**Comment by polymorpher** [comment]
Yes, that works. Thanks!
