### ISSUE TITLE
Parsers are off? 

### ISSUE THREAD

**Issue by danyaljj** [clulab/processors#149]
The demo seems to be off: 
http://agathon.sista.arizona.edu:8080/discp/

**Comment by MihaiSurdeanu** [comment]
@hickst: can you please answer?

**Comment by hickst** [comment]
Thanks for letting us know the website was not working properly. It should now be available again.

Unfortunately, we no longer run the discourse parser demo, which you were attempting to access. The demo software got out of date and we did not see anyone trying to access it for a long time.

**Comment by danyaljj** [comment]
I see ... thanks for clarification.
