### ISSUE TITLE
Serialization not working

### ISSUE THREAD

**Issue by omidb** [clulab/processors#15]
Thanks for the wrapper, I got exception in this last line:

`proc.parse(doc)`
    `val ser = new DocumentSerializer`
    `val out1 = ser.save(doc)`

I copied this from test files, the exception is :
`java.lang.ClassNotFoundException: scala.collection.GenTraversableOnce$class`

**Comment by myedibleenso** [comment]
There hasn't been a response since Jul 8, 2014.  I'm going to close this issue, but we can reopen again if needed.  I don't think this was the issue here, but changes to `Document` (infrequent though they may be) can break serialization across versions.
