### ISSUE TITLE
new travis images

### ISSUE THREAD

**Issue by marcovzla** [clulab/processors#158]
We are currently using the old travis images by including `group: deprecated-2017Q2` in `.travis.yml`, but these will only be available until September 1st, 2017, so we need to replace them.

See https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch

**Comment by myedibleenso** [comment]
So Sept. 1 has come and gone, but travis still seems to be working...has this just been pushed back?

**Comment by hickst** [comment]
Why is that parameter even needed? Reach does not use it and Travis is working fine for Reach. Was there something special about those images that Processors required?

**Comment by kwalcock** [comment]
We haven't been using Travis for quite some time, so I'm closing.
