### ISSUE TITLE
Version update for scala 2.11.1

### ISSUE THREAD

**Issue by omidb** [clulab/processors#16]
Hi, 
would you please make it available for Scala 2.11 on maven repository?

Thanks for the good library

**Comment by omidb** [comment]
do you guys have dependency to specific lib that you cannot have both 2.10.x and 2.11.x support?

**Comment by MihaiSurdeanu** [comment]
No library dependencies. But we had to modify a little bit of our code, support for which changed in 2.11, which is why we support only 2.11 now.

**Comment by vito-c** [comment]
Hi is there a 2.11 repo yet?

**Comment by MihaiSurdeanu** [comment]
Hi,
We support 2.11 exclusively for the past several versions now...
Mihai
