### ISSUE TITLE
Configurable models (PoS tagger, parser, etc.) for `CoreNLPProcessor` and `CluProcessor`

### ISSUE THREAD

**Issue by myedibleenso** [clulab/processors#172]
It would be convenient to be able to use `CoreNLPProcessor` with different `corenlp` models (ex. models for Spanish).  This would make it easier to support other languages and experiment with different training sets.

**Comment by MihaiSurdeanu** [comment]
Done for CluProcessor.
Hard to do for CoreNLP, so closing this.
