### ISSUE TITLE
Upgrade to CoreNLP 3.5

### ISSUE THREAD

**Issue by matanster** [clulab/processors#18]
[Stanford CoreNLP 3.5](http://nlp.stanford.edu/software/corenlp.shtml) has brought about some novelties, and upgraded to Java 8 (see [Upgrade to Java 1.8; add annotators for dependency parsing, relation extraction](http://nlp.stanford.edu/software/corenlp.shtml#History)). https://mailman.stanford.edu/pipermail/java-nlp-user/2014-October/006457.html provides some upgrade advice and more discussion of the additions/changes. It would be very nice to upgrade sistanlp to use it, and publish to maven.

Not sure how much Scala support for Java 8 is needed though, as official Scala releases only included [_some_ support](http://scala-lang.org/news/2.11.1), maybe that is enough.

**Comment by MihaiSurdeanu** [comment]
Two comments:
1. We already have a very stable dependency parser included in FastNLPProcessor, so the new features in 3.5 are not extremely exciting for us.
2. We are in the process of upgrading to newer Java, but some concurrency unit tests fail with Java 1.7. We are trying to fix these before upgrading.

**Comment by MihaiSurdeanu** [comment]
Done.
