### ISSUE TITLE
Dataset should extend Traversable

### ISSUE THREAD

**Issue by myedibleenso** [clulab/processors#188]
It would be convenient if [`Dataset`](https://github.com/clulab/processors/blob/54d8e7b96bc0f03a9812e09bd0f360d96c241ad0/main/src/main/scala/org/clulab/learning/Dataset.scala) extended [`Traversable`](http://docs.scala-lang.org/overviews/collections/trait-traversable.html).  This would simplify access to each `Datum` via `foreach`, `map`, etc.

Right now for a `Dataset` (`ds`) I'm using something like `ds.labels.indices.map(data.mkDatum)`.

**Comment by kwalcock** [comment]
@myedibleenso, this was finally done and is currently available in the master branch and will be in the next release!  You would need to change your code to something like `ds.map` to make use of it.
