### ISSUE TITLE
Multiple Word2vec implementations

### ISSUE THREAD

**Issue by dispalt** [clulab/processors#198]
Is there a way to hook in to plug in my own word2vec implementation?  Specifically I was looking to use dl4j's version.  Right now I've subclasses some classes and it's gross but it works.  I was wondering if there was plans to make that more configurable, either by adding my own rules (simScore2), or by making the implementation less coupled.

**Comment by myedibleenso** [comment]
Hi,

Glad to see you're using Odin!  Yes, we can definitely make that easier to do.  `EmbeddingsResource` just needs some `similarity` method that takes two strings and returns a Double. 

We'll consider a few options for specifying an implementation (ex. changes to the master file vs. an `OdinConfig` parameter to the constructor for `ExtractorEngine` vs. dependency injection, etc.).

**Comment by dispalt** [comment]
Sounds great, thanks!
