### ISSUE TITLE
Multithreading and support for Senna!?

### ISSUE THREAD

**Issue by dkaushik96** [clulab/processors#219]
Hi, I think it would be great to include multithreading support, it would help especially when number of documents is quite high.

Further, can we have support for Senna? Stanford POS and NER put a lot of weight on capitalization of text as a feature, which does not help in case of noisy user generated text. I've personally tested Senna over such data and found it more useful.

Lastly, is it possible for one to switch off dependency parsing over the document if the rules don't depend on dependency parse?

**Comment by myedibleenso** [comment]
Hi.

>I think it would be great to include multithreading support, it would help especially when number of documents is quite high.

All of the processors currently available are thread-safe, so this can be achieved using parallel collections (ex. `.par`) or with Actors. In fact, we do this sort of thing a lot in the projects that use this library!

>can we have support for Senna?

SENNA is written in C, right?  It would be great to have an SRL parser in `processors` (plus it could be used in `Odin` rules).  Unfortunately, being written in C makes SENNA difficult to bundle in a jar.  That said, you can definitely call SENNA and use its output to build a [`processors.Document`](https://github.com/clulab/processors/blob/master/main/src/main/scala/org/clulab/processors/Document.scala).  You might consider creating a custom `Processor` that calls SENNA.  You'd need to implement [the `Processor` trait](https://github.com/clulab/processors/blob/master/main/src/main/scala/org/clulab/processors/Processor.scala), or inherit from something like `CluProcessor` and override the relevant methods (ex. `tagPartsOfSpeech`, `recognizeNamedEntities`, etc.).


>Lastly, is it possible for one to switch off dependency parsing over the document if the rules don't depend on dependency parse?

Do you want to avoid loading the parsing models, or simply avoid a `.parse()` call?  The `ShallowNLPProcessor` does not parse documents.  Would a method like this work for you?

```scala
def shallowAnnotate(text: String, proc: Processor): Document = {
  val doc = proc.mkDocument(text)
  proc.tagPartsOfSpeech(doc)
  proc.lemmatize(doc)
  proc.recognizeNamedEntities(doc)
  //proc.parse(doc)
  proc.chunking(doc)
  //proc.resolveCoreference(doc)
  //proc.discourse(doc)
  doc.clear()
  doc
}
```
What rules are you referring to, @dkaushik96?  Odin rules?

**Comment by dkaushik96** [comment]
Yes, I think the ShallowNLPProcessor would work. I don't remember if multithreading or shallowannotate were discussed either in the manual or the Python tutorial. This is really helpful though. Thanks!

**Comment by MihaiSurdeanu** [comment]
Closing for now.
