### ISSUE TITLE
Binary incompatibility as a result of using nlptools-stem-morph (deprecated)

### ISSUE THREAD

**Issue by polymorpher** [clulab/processors#233]
The package `nlptools-stem-morph` is one of the core dependencies of this project, but it is deprecated (https://github.com/knowitall/nlptools).  `nlptools-stem-morph` only supports Scala up to 2.10 and many of its dependencies (and dependencies of dependencies) are fixed at the version against Scala 2.10. However some of them already published new versions, and they may be incompatible with old version. In particular, the package `scopt` is troublesome. For instance, if my project depends on scopt_2.11 or scopt_2.12, the project would fail to load or compile because of conflicts between that and scopt_2.10. If I force my project to use scopt_2.10, it would throw errors at runtime (e.g. `Exception in thread "main" java.lang.NoClassDefFoundError: scala/Product$class`). This is just one of the examples and there might be more issues like this, unrelated to the particular package `scopt`.

**Comment by MihaiSurdeanu** [comment]
Hi @polymorpher,
You're right. Did you manage to find the source code for the stem-morph package? I looked around the newer code and couldn't find. If you do, please let me know. I would include the source in processors (if licensing permits), to solve this issue. I can handle the latter; I just can't find the source.

**Comment by polymorpher** [comment]
Thanks for looking into this. I will let you know if I find the source.

For my own project, I created a temporary workaround by forking scopt and renaming the package.

**Comment by MihaiSurdeanu** [comment]
@kwalcock: when you have some time, not urgent at all, can you please try to find the source code for nlptools-stem-morph? This used to be part of a project at UW, but it seems that IIT took over that open source project.

**Comment by kwalcock** [comment]
According to processors/main/build.sbt, we're using

"edu.washington.cs.knowitall.nlptools"  %  "nlptools-stem-morpha_2.10"  %
"2.4.5", // for lemmatization

If the idea is to get the source for that, it can be extracted from the jar
files in an emergency or I see that it can be downloaded from

https://github.com/knowitall/nlptools/releases/tag/v2.4.5

If we're looking for an updated version that may have corrected an issue
that was found, I'll have to look further at IIT.

**Comment by MihaiSurdeanu** [comment]
Thanks @kwalcock! I'll see what I can do from here.

**Comment by MihaiSurdeanu** [comment]
Almost there, in branch "morpha". I copied the jflex output here, to avoid the dependency. But how the heck do you call a jflex parser? It's been more than 15 years since I've used it...
This is not it:
https://github.com/clulab/processors/blob/morpha/main/src/main/scala/org/clulab/processors/clu/CluProcessor.scala#L253

@kwalcock: do you know? No big deal if you don't. I'll look it up.

**Comment by kwalcock** [comment]
Not offhand, but if you give up or simply delegate, I'll figure it out, of course.

I wanted to say that if you *happen* to be working on processors, you might take a look at one certain outstanding pull request.

**Comment by MihaiSurdeanu** [comment]
Fixed in PR #235.
Will be available in release 7.2.1
