### ISSUE TITLE
Symbol table error

### ISSUE THREAD

**Issue by maxaalexeeva** [clulab/processors#234]
When I try to run CluProcessor (annotate()) on the attached file, I get the error below. I used Try to go around it, but I am still not sure what is wrong with the text file that won't let the annotator run. As far as I can tell, it breaks somewhere around line 4. Let me know if I should include everything that printed out after the error statement to make this more understandable. Thanks!

`13:29:49.956 [run-main-0] DEBUG o.c.p.clu.syntax.MaltWrapper - Using modelURL for parsing model en-forward-nivrestandard: file:/tmp/processors-130562231008181-21-0/en-forward-nivrestandard.mco
[error] (run-main-0) org.maltparser.core.symbol.SymbolException: Symbol table error: empty string cannot be added to the symbol table
org.maltparser.core.symbol.SymbolException: Symbol table error: empty string cannot be added to the symbol table
`

[text.txt](https://github.com/clulab/processors/files/1845777/text.txt)

**Comment by MihaiSurdeanu** [comment]
Can you please include how you use this? Is this a separate project? if so,
can you please include the build file?
I suspect you don't have processors_modelsmain in the path, but I'm not
sure.

**Comment by maxaalexeeva** [comment]
It is a separate project. I attempt to annotate some lines.
`val proc:Processor = new CluProcessor() 
(some code)
val line_doc = proc.annotate(line)`

buildfile:
`name := "testing"
scalaVersion := "2.11.8"
libraryDependencies ++= Seq(

  "org.clulab" %% "processors-main" % "6.1.3",
  "org.clulab" %% "processors-corenlp" % "6.1.3",
  "org.clulab" %% "processors-modelsmain" % "6.1.3",
  "org.clulab" %% "processors-odin" % "6.1.3",
  "org.apache.commons" % "commons-math3" % "3.3",
  "org.scalanlp" %% "breeze-natives" % "0.13.2",
  "org.scalanlp" %% "breeze-viz" % "0.13.2",
  
  "com.typesafe.scala-logging" %% "scala-logging" % "3.7.2",
  "com.github.fommil.netlib" % "all" % "1.1.2",
  "com.github.fommil.netlib" % "native_ref" % "1.1",
  "org.apache.tika" % "tika-parsers" % "1.11" excludeAll(                   
    ExclusionRule(organization = "org.bouncycastle"),
    ExclusionRule(organization = "commons-logging"),
    ExclusionRule(organization = "org.apache.cxf")
  ),
  "org.apache.tika" % "tika-core" % "1.11",                                
  "org.json4s" %% "json4s-native" % "3.6.0-M2",
  "org.json4s" %% "json4s-jackson" % "3.6.0-M2"
)
`

**Comment by MihaiSurdeanu** [comment]
Oh, can you please try version 7.2.0 instead of 6.1.3?

**Comment by maxaalexeeva** [comment]
For which of the dependencies? All of the 6.1.3 ones? Some of them?
[error] (*:update) sbt.ResolveException: unresolved dependency: org.clulab#processors-main_2.11;7.2.0: not found
[error] unresolved dependency: org.clulab#processors-corenlp_2.11;7.2.0: not found
[error] unresolved dependency: org.clulab#processors-modelsmain_2.11;7.2.0: not found
[error] unresolved dependency: org.clulab#processors-odin_2.11;7.2.0: not found

**Comment by MihaiSurdeanu** [comment]
Sorry, try to do what this project does:
https://github.com/clulab/eidos/blob/master/build.sbt

**Comment by MihaiSurdeanu** [comment]
I believe this was fixed.
Closing for now.
