### ISSUE TITLE
"damage" matched as entity

### ISSUE THREAD

**Issue by danebell** [clulab/processors#25]
There are a lot of damage-binding proteins and other entities with "damage" in their name, but I don't think "damage" should be matched as it is being, e.g. in "Two of these sites ( Ser966 and Ser957 in Smc1 ) have been shown to be phosphorylated by the ATM kinase in response to DNA damage."

**Comment by danebell** [comment]
I've prepared an exhaustive list of words that overlap between capitalized protein names and English words. This isn't filtered for word frequency, so use with care -- _aah_ is unlikely to appear in a biomedical text except as a protein name, but that might not be the case for _cat_, _ape_, _chimp_, etc. 
[overlap.txt](https://github.com/clulab/processors/files/143556/overlap.txt)

**Comment by MihaiSurdeanu** [comment]
Hi @danebell: I would like to add this list to bioresources and use it to filter out false positives in the rule-based NER. But, at this point, it seems too over-inclusive. Can you please do another pass over it, and keep just words that are likely to appear as non-proteins in bio texts? For example, I would remove the first 9 entries (they are likely to be only used as proteins), but keep ACT, ANT, etc.

**Comment by danebell** [comment]
Yes, I can definitely do this, but there are over 1000 entries, so if it's okay, I will wait for at least a week to do so.

**Comment by MihaiSurdeanu** [comment]
Agreed, it can wait. I suspect that less than 10% of this are actually
relevant in this list (the rest are valid protein names that are unlikely
to be used otherwise in bio texts).

**Comment by MihaiSurdeanu** [comment]
closed by the addition of the NER stop list in bioresources 1.1.9.
