### ISSUE TITLE
Specify grammar file for CluProcessor tokenizer via config

### ISSUE THREAD

**Issue by myedibleenso** [clulab/processors#289]
As @danebell and others can attest, when considering differences observed across domains, registers, corpora, and tasks, a single token grammar per language is unlikely to fit all cases.  For that reason, I propose we alter `CluProcessor` such that its tokenizer is determined by specifying the grammar file's location from the config (ex. `*.tokenizer.grammar = ???`): 

- https://github.com/clulab/processors/blob/6cf2291418c063ef9a429708ab064b2842a0bb20/main/src/main/scala/org/clulab/processors/clu/CluProcessor.scala#L44-49

Since `CluProcessor` uses [ANTLR 4 grammars](https://www.antlr.org/) for tokenization and sentence segmentation, this seems like a reasonable change to make.  Doing so would make it even easier to develop custom processors for very specialized tasks.

**Comment by kwalcock** [comment]
@myedibleenso, a [change](https://github.com/clulab/processors/commit/c2e2ba8e8743d2c36ccc87255c14f3fa498e36f7#diff-5f96fe6519f4a0aaeddcbffa28656b1dee1bd10725cbc7b883a1e2c31128b7c3) made to CluProcessor after submission of your issue allows the user to supply a tokenizer when the CluProcessor is constructed.  That tokenizer could be based on an alternate ANTLR grammar or anything else and could be configured as suggested or hard-coded, onbeknownst to CluProcessor.  Would that serve your purpose here?  In other words, is the issue now obsolete?

**Comment by myedibleenso** [comment]
I think so.  Thanks, @kwalcock !
