### ISSUE TITLE
Hashing of sentences takes up too much time

### ISSUE THREAD

**Issue by kwalcock** [clulab/processors#294]
Here's an incomplete record of emails regarding this issue which Becky and Marco discovered:

![image](https://user-images.githubusercontent.com/8679738/51404743-95046d00-1b11-11e9-8357-0fa0decdc1bd.png)

Yeah, those vars need to be made private, and accessed through setter methods, who will also reset the computed hash value. 
Should not be too hard to change… More annoying than hard, I think.

> On Jan 3, 2019, at 10:09 AM, Keith Alcock <keith@keithalcock.com> wrote:
> 
> Yes, probably, unless it is too problematic because of all the vars.
> 
> 
> On Thu, Jan 3, 2019 at 10:41 AM Mihai Surdeanu <surdeanu@gmail.com> wrote:
> I see… But Sentence hashing still matters, even if (optimally) just for the sentences that contain mentions. 
> So it’s probably still worth it to implement a caching mechanism for the hash value, no?
> 
> > On Jan 2, 2019, at 11:00 PM, Keith Alcock <keith@keithalcock.com> wrote:
> > 
> > I would think that most of the hashing that occurs with Eidos is just to make sure that Mentions are not used twice.  Mention.calculateHashCode does a complete hash of the document, including all sentences
> > 
> > val h4 = mix(h3, document.equivalenceHash)
> > 
> > even when we know there is only a single document in question.  When this is the case, probably a plain document.hashCode (or nothing at all) would do.  I can imagine it being difficult to separate the two cases cleanly, though.
> > 
> > 
> > 
> > On Sat, Dec 29, 2018 at 1:11 PM Rebecca <bsharp@email.arizona.edu> wrote:
> > While the synchronized NN is the main slowdown pretty much for sure, we did notice something else that may really speed things up if we can address it. 
> > 
> > Sentence equivalence hash is a def, not a val, so gets computed over and over.  This actually seems to account for at least 20-30% of the actual runtime (we didn't keep expanding):
> > 
> > 
> > 
> > maybe one solution is making it a val, a lazy val, or a var. but we don't know.  Either way, it is a lot of time spent computing hashes and maybe there is an opportunity for optimization.
> > 
> > Thanks guys!
> > Becky and Marco
> 
>

**Comment by myedibleenso** [comment]
@kwalcock, one reason this wasn't cached from the beginning is that there is nothing stopping someone from altering an element in any of the token attribute arrays (words, tags, etc.).  If any of this data is mutated, the approach as-is will reflect the change.

It might make sense to only address this in Eidos, since you are already using custom Mentions (and docs?).

**Comment by kwalcock** [comment]
Right.  So often one would use the suggested getter and setter (of otherwise immutable values) and trigger a dirty hash code when the setter is called.  It seems better to have the sentence remember that it has been changed than to have each client remember to tell the sentence to update the hash code each time that it changes the sentence.  Adding getter and setter code will probably disrupt clients near and far, though.  Perhaps as an experiment, the EidosMention can cache the codes instead.

**Comment by kwalcock** [comment]
A different approach is to do like Mentions and include methods like newWithLemmas() and return a new sentence with the missing Option value filled in.  Right now Eidos would not like that because the time and geo functions operate on sentences, editing their norms, long after the sentence references have been stored in all sorts of Mentions.  It seems like those references would all have to be updated and that would be a problem.

**Comment by MihaiSurdeanu** [comment]
I prefer the classic solution of getter/setter methods. The setter methods would regenerate the hash, so it's always up to date. Of course, all the vars would become private.

**Comment by kwalcock** [comment]
I notice that my cachedHashCode in Mention is incorrect if the hash of the sentence changes :-(  Probably this doesn't matter because sentences are not being copied and changed independently.  If they are equal once, they stay equal.

**Comment by kwalcock** [comment]
It may be that a different kind of equivalence is needed or could at least be useful.  For most use cases, the sentences are equivalent if they have the same value for raw or to be extra careful, startOffsets, endOffsets, and words (the vals).  The rest (vars) just indicate that the same/equivalent sentence is in some different state of the processing pipeline.  The hash code, at least that used by Mention, could be based on just these fixed variables.

**Comment by myedibleenso** [comment]
You're right that there are different degrees/forms of equivalence.  I've used a strict measure mostly to differentiate between types of annotation (ex. syntactic parses).  While I think it is important to keep this complete check, there's no reason other forms can't be used for different applications.  For mentions, I only used `equivalenceHash` through mixin of a trait in implicits: 

- https://github.com/clulab/processors/blob/4890c0c64c9d107666330a1d8e3ca7371edc8729/odin/src/main/scala/org/clulab/odin/serialization/json/package.scala

Perhaps we should remove `equivalenceHash` from `Sentence`?

**Comment by kwalcock** [comment]
How about I add a new, lazily calculated hash method across some/all the vals to Sentence?  It needs to get called, I think, from Mention.calculateHashCode, possibly via Document.equivalenceHash.  If that one shouldn't change (it sort of looks like sentence order is intentionally ignored there, strangely) then there could eventually be a matching hash in Document that calls the one in Sentence.  This might be sufficient to test whether the performance indeed improves, if there are unintended consequences, etc.

**Comment by myedibleenso** [comment]
Sounds good to me.

**Comment by kwalcock** [comment]
@bsharpataz and @marcovzla were definitely onto something.  Here are some initial comparisons for runs across 52 documents showing that a change in hashing can halve processing time (9:37 minutes down to 4:13).  Unfortunately, the timenorm functionality would still be the slowest part and that isn't affected by the change.  It should help eidos unit testing, which runs without timenorm, and any other project unrelated to timenorm.

```
On 52
	Before
		None
			sbt "runMain org.clulab.wm.eidos.apps.ExtractFromDirectory ../corpora/Doc52/txt ../corpora/Doc52/jsonld-time-before-none"
			09:20:27.896 [run-main-0] INFO  org.clulab.wm.eidos.utils.Timer$ -  Time 0:00:09:37.532
		Grounding
			sbt "runMain org.clulab.wm.eidos.apps.ExtractFromDirectory ../corpora/Doc52/txt ../corpora/Doc52/jsonld-time-before-gnd"
			09:39:06.504 [run-main-0] INFO  org.clulab.wm.eidos.utils.Timer$ -  Time 0:00:09:53.721
		Grounding and geo
			sbt "runMain org.clulab.wm.eidos.apps.ExtractFromDirectory ../corpora/Doc52/txt ../corpora/Doc52/jsonld-time-before-gnd-geo"
			10:21:01.271 [run-main-0] INFO  org.clulab.wm.eidos.utils.Timer$ -  Time 0:00:12:15.754
		Grounding and geo and time
			sbt "runMain org.clulab.wm.eidos.apps.ExtractFromDirectory ../corpora/Doc52/txt ../corpora/Doc52/jsonld-time-before-gnd-geo-time"
			11:08:06.104 [run-main-0] INFO  org.clulab.wm.eidos.utils.Timer$ -  Time 0:00:42:31.420
	After
		None
			sbt "runMain org.clulab.wm.eidos.apps.ExtractFromDirectory ../corpora/Doc52/txt ../corpora/Doc52/jsonld-time-after-none"
			11:39:45.367 [run-main-0] INFO  org.clulab.wm.eidos.utils.Timer$ -  Time 0:00:04:13.447
		Grounding
			sbt "runMain org.clulab.wm.eidos.apps.ExtractFromDirectory ../corpora/Doc52/txt ../corpora/Doc52/jsonld-time-after-gnd"
			11:51:40.535 [run-main-0] INFO  org.clulab.wm.eidos.utils.Timer$ -  Time 0:00:04:44.629
		Grounding and geo
			sbt "runMain org.clulab.wm.eidos.apps.ExtractFromDirectory ../corpora/Doc52/txt ../corpora/Doc52/jsonld-time-after-gnd-geo"
			12:18:16.062 [run-main-0] INFO  org.clulab.wm.eidos.utils.Timer$ -  Time 0:00:06:54.880
		Grounding and geo and time
			sbt "runMain org.clulab.wm.eidos.apps.ExtractFromDirectory ../corpora/Doc52/txt ../corpora/Doc52/jsonld-time-after-gnd-geo-time"
			13:19:08.819 [run-main-0] INFO  org.clulab.wm.eidos.utils.Timer$ -  Time 0:00:38:00.068
```

**Comment by MihaiSurdeanu** [comment]
Very nice.

**Comment by myedibleenso** [comment]
@kwalcock , is this now resolved?
