### ISSUE TITLE
unicode_to_ascii.tsv

### ISSUE THREAD

**Issue by bgyori** [clulab/processors#30]
I am getting a error from BioNLPPreProcessor:
```
Exception in thread "main" java.lang.AssertionError: assertion failed: Failed to find resource file edu/arizona/sista/processors/bionlp/unicode_to_ascii.tsv in the classpath!
	at scala.Predef$.assert(Predef.scala:165)
	at edu.arizona.sista.processors.bionlp.BioNLPPreProcessor$.loadUnicodes(BioNLPPreProcessor.scala:77)
...
```
indeed the file unicode_to_ascii.tsv is not on that path. Should this file be checked into the repo or am I missing something?

**Comment by MihaiSurdeanu** [comment]
Hi Ben,
The file is there, see:
https://github.com/clulab/processors/blob/master/models/src/main/resources/edu/arizona/sista/processors/bionlp/unicode_to_ascii.tsv

Maybe you need to do a git pull, to bring your code up to date? 
Or your clone is corrupted, and you need to git clone again?
Another possibility: are you seeing this error when you run the reach project? If so, you have to make sure you did "sbt publishLocal" in processors first.

Let us know.
Thanks,
Mihai

**Comment by bgyori** [comment]
Hi MIhai, thanks, your comment helped to figure out that the problem was in my version of the models jar file and now that I corrected that it works fine!

**Comment by MihaiSurdeanu** [comment]
Cool.

Btw, we will have official and stable releases of processors and reach soon, which should simplify things a bit.
