### ISSUE TITLE
A DirectedGraph should always have at least one root

### ISSUE THREAD

**Issue by myedibleenso** [clulab/processors#303]
## Problem
The English `CluProcessor` produces a rootless parse for the following sentence:
>By increasing N availability to the plant, band placement allowed the use of a onethird to two-thirds N split application which increased plant N concentration during the reproductive stage, particularly in direct seeded rice.

We have observed this in a number of sentences, so @danebell or I can provide additional examples as needed.  

All valid dependency parses should produce at least one root.  

Whether or not you agree from a theoretical standpoint, other code in `processors` (ex. `DependencyUtils`) assumes that all parses will have at least one root.

### Proposed solutions
Here are a couple of options that come to mind...
1. Devise a heuristic for assigning a root (or roots) when the parser fails to do so.
2. Whenever a parse is produced that lacks a root, set the parse to `None`.

**Comment by kwalcock** [comment]
This issue was causing reach to crash recently.  We have code that expects there to be a root.

**Comment by MihaiSurdeanu** [comment]
I can handle this, but:
1. It would be nice to see a stack trace in Reach.
2. The fact that the old CluProcessor produces a rootless parse is no longer relevant, as that code is no longer maintained. The new code in v8 should be much much better. Is there a stack trace from the latest released processors?

**Comment by kwalcock** [comment]
It has to do with this recent patch near findHeadStrict: https://github.com/clulab/reach/pull/724/commits/26ee8b91ca2a264fc2a348c9768126c8be29bb8e

A breakpoint in the exception handler right there should catch it in the act.  If one adds before the `None` a try again (`DependencyUtils.findHeadStrict(span, sent)`), one should be able to observe it fail all over again.

The code is executed with the TestCrashes unit test for the file `PMC7040422`.  One can disable all the other tests.  I can make a branch with these changes if it would help.

I was surprised that this seems to be a known issue.

**Comment by MihaiSurdeanu** [comment]
Please make the branch and pass it to me.

**Comment by kwalcock** [comment]
It's the reach branch headlessDep.  There's a place for a breakpoint in LinguisticPolarityEngine that will be hit if TestCrashes runs.

**Comment by MihaiSurdeanu** [comment]
Thanks!
I'll take a look after a long stream of meetings...

**Comment by kwalcock** [comment]
If debugging is more interesting than meetings...

**Comment by MihaiSurdeanu** [comment]
sbt 'testOnly org.clulab.reach.export.TestCrashes' in the headlessDep branch passes on my machine...

**Comment by kwalcock** [comment]
That's intentional.  These lines can be commented out if you want it to crash, but it will be too late to do anything about it after it does.

https://github.com/clulab/reach/blob/f18cd6ab6af2c3838c29ff5499562d0a2ea6ddd1/main/src/main/scala/org/clulab/polarity/LinguisticPolarityEngine.scala#L96-L98

**Comment by MihaiSurdeanu** [comment]
- This issue has been fixed in the latest processors master, 8.2.26-SNAPSHOT.
- I added a test which passes with this version in the `headlessDep` branch in reach.

If this seems Ok with you @kwalcock, we can release processors, and update the build file here for that.

**Comment by kwalcock** [comment]
Thank you!  I'm trying very hard to resist rearranging a few of the lines in CoreNLPUtils.  Since @myedibleenso filed the issue and knows about other times it has been encountered, he is being pinged.  Does that mean *I* should release?  Is this bug fix worthy?  Perhaps #450 could be merged in as well.  It is waiting approval in case I did a no-no.

**Comment by MihaiSurdeanu** [comment]
Yes, please merge #450 as well.

**Comment by myedibleenso** [comment]
I don't have any additional test cases for this at the ready.  I'm still surprised this is possible, but then again I'm not sure what approach CoreNLP is using to generate the parse these days. 

@kwalcock , what do you want to change in CoreNLPUtils?

**Comment by kwalcock** [comment]
Egged on by @myedibleenso, I put some changes into the branch kwalcock-roots.  It's a freeby, off the clock, which can be thrown away unless is looks worthwhile.  It did occur to me later that the List.distinct instead of Set.toList might prevent some future repeatability problems.

**Comment by myedibleenso** [comment]
LGTM.  It could make things easier to debug.

**Comment by MihaiSurdeanu** [comment]
LGTM too. Please merge.
