### ISSUE TITLE
Caseless parsing model

### ISSUE THREAD

**Issue by vrcod** [clulab/processors#31]
Can this library be used for parsing tweets? I'm mostly interested in extracting locations, dates, names and if possible more. There seems to be a relevant question on Stanford NLP FAQ: http://nlp.stanford.edu/software/parser-faq.shtml#ca

**Comment by MihaiSurdeanu** [comment]
Not really. The Stanford NER and parser were trained on "regular" text coming from news and scientific articles. For parsing tweets, take a look at: http://www.ark.cs.cmu.edu/TweetNLP/
