### ISSUE TITLE
Is there any way to recover the RST tree from printed discourse tree string

### ISSUE THREAD

**Issue by cs329yangzhong** [clulab/processors#324]
I can successfully generate the discourse tree with Fast-processor, however, I just wondered if there is any way to recover those back to the tree objects. Since I want to traverse through the RST tree and see the relationship between different sentences.

**Comment by MihaiSurdeanu** [comment]
Yes, Document.discourseTree contains the discourse tree as an actual tree data structure:

https://github.com/clulab/processors/blob/master/main/src/main/scala/org/clulab/processors/Document.scala#L22

**Comment by cs329yangzhong** [comment]
Thanks! but I am curious about is there some code to recover the printout string back to the tree structure? like `func readlines(file){ \* read the indentation file and convert it back to discourse tree *\}` Or would you mind pointing me to the specific data structure file for both edu nodes and tree?

**Comment by MihaiSurdeanu** [comment]
We don't have code for that.

But the data structure for the discourse tree is here:
https://github.com/clulab/processors/blob/master/main/src/main/scala/org/clulab/discourse/rstparser/DiscourseTree.scala#L16

**Comment by cs329yangzhong** [comment]
Great, thanks! I might need to write my own reader.
