### ISSUE TITLE
processors does not publishLocal for scala 2.11

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/processors#336]
We need still need the 2.11 compile for Reach. But when I do sbt publishLocal, processors only publishes the scala 2.12 compile. @kwalcock or @marcovzla: can you please look into this?

I am working on a Reach bug, which depends on this. Thank you!
See:
https://github.com/clulab/reach/issues/634

**Comment by kwalcock** [comment]
Does it work with +publishLocal?

https://stackoverflow.com/questions/35270578/sbt-cross-publish-from-build-sbt

**Comment by MihaiSurdeanu** [comment]
@kwalcock: it does. Thanks!
