### ISSUE TITLE
String intern

### ISSUE THREAD

**Issue by qiuwei** [clulab/processors#34]
Hi, 
In the Reame, it's mentioned that 

> Furthermore, we used our own implementation to intern strings (i.e., avoiding the storage of duplicated strings multiple times).

However, in the recent release 5.8.0, I see

> We no longer intern Strings by default in BioNLPProcessor.

What's the reasoning behind it?

**Comment by MihaiSurdeanu** [comment]
One drawback of interning strings is that that cache continues to grow for the lifetime of the program. The most common usage for BioNLPProcessor (for us, at least) is within the Reach project where we process hundreds of thousands of papers in the same process. In this setup, the interning memory becomes too big. 

Nevertheless, if you prefer to continue to intern strings, you can enable interning simply by setting the boolean parameter in the constructor back to true.
