### ISSUE TITLE
Re TokenizerStepContractions, TODO: this is slow. This should be handled in the Antlr grammar

### ISSUE THREAD

**Issue by kwalcock** [clulab/processors#342]
The TODO comment was found in the code, so here is a reply.

It may be that these are somehow optimized away, but when regular expressions are involved I've sometimes had success speeding things up by moving them to the class or even object level.  So, instead of
```
  override def process(inputs:Array[RawToken]): Array[RawToken] = {
    for(input <- inputs) {
      else if ("""^[wW][oO][nN]'[tT]$""".r.findFirstIn(input.raw).isDefined) {
```
it might be
```
class TokenizerStepContractions extends TokenizerStep {
  val wont = """^[wW][oO][nN]'[tT]$""".r

  override def process(inputs:Array[RawToken]): Array[RawToken] = {
    for(input <- inputs) {
      else if (wont.findFirstIn(input.raw).isDefined)  
```
This *could* prevent "recompilation" of the regular expression for every iteration of the loop.  The may also be a flag for case insensitive matching which could make the expressions more readable and could affect performance.  Alternatively, the input could be normalized to one case or the other.

**Comment by kwalcock** [comment]
Regular expressions are sometimes cached and looked up, probably based on the string that specified them, but just storing them in a variable would still eliminate the lookup.

**Comment by MihaiSurdeanu** [comment]
Thanks! Good catch. I'll take a look soon.
If you already addressed this, please let me know.

**Comment by kwalcock** [comment]
It may need to go all the way to the pattern:
```
val eopPattern: Pattern = """^(\.?)(\s*)\n(\s*)\n(\s*)$""".r.pattern // End of paragraph
```
I may be suggesting an additional change for the benefit of Eidos that would justify a 0.0.1 version change.  They might be checked in at the same time.

**Comment by kwalcock** [comment]
I was revising the code in [TokenizerStepContractions](https://github.com/clulab/processors/blob/master/main/src/main/scala/org/clulab/processors/clu/tokenizer/TokenizerStepContractions.scala) to make it faster, smaller, and simpler, but then I was worried about whether it was getting the correct or best answer anyway and then why it was doing this in the first place.  I *think* it is done to help other components figure out ambiguous contractions (e.g., 's may indicate possessive, is, has, or even does).  There are also some "productive" contractions that can go on almost anything (at least in speech), but which might without separation result in words out of vocabulary: "Shannon'll not be in today."  Shannon'll isn't in the dictionary, but both of the parts are.  I'm doubtful, though, because that theory doesn't hold for 've.  'd is separated and seems productive, but then it is also ambiguous (would or had and maybe did).

Anyway, here is a small list of problem cases:

* let's might not be divided into let 's, but be kept whole or divided into "let us".  Which?
* can't shouldn't be "ca not" but "can not"
* ain't shouldn't be "ai not" but be left alone.  The ai is even ambiguous.
* shan't shouldn't be "sha not" bit instead "shall not"
* aren't has an exception in "aren't I" when it would be am and in general the word order with not would need to be changed in a question: aren't you -> are you not.  The tokenizer doesn't look at more than one word at a time and this is probably out of bounds.
* It is possible to distinguish between genitive 's and non-genitive in some cases, but there is still ambiguity especially in British English, because it can mean is, has, or apparently even does (in why's, but perhaps only in speech).  In particular, he's, she's, it's, there's, and who's cannot be possessive because for that we have his, her, its, their, and whose.  In some cases it is not possessive because the thing can't possess: here's, how's,  when's, where's, which's, why's.  Since there is still ambiguity, the parts may still need to be separated: when's -> when is or when does.
* Lists at places like [grammerly](https://www.grammarly.com/blog/contractions/) and [wikipedia]( https://en.wikipedia.org/wiki/Wikipedia:List_of_English_contractions) think the 'd in that'd and what'd can only be would and where'd can only be did, but I'm not convinced.
* Double contractions like we’d’ve and wouldn’t’ve aren't being handled.  They probably aren't encountered.

It seems safe to handle the first four of those.  Others like 've and 're are easy, but depend on the why.  Should they be changed to have and are?

FYI @MihaiSurdeanu

**Comment by kwalcock** [comment]
I *think* the line
```scala
            tokens += RawToken("will", input.beginPosition, input.endPosition)

```
is incorrect because it is changing the raw value to "will".  It should be more like
```scala
            tokens += RawToken(input.raw, input.beginPosition, "am")
```
in which the word is transformed to "am" while keeping the same raw value.

**Comment by MihaiSurdeanu** [comment]
Thanks @kwalcock !
- I agree with moving the regexes at object level.
- The first parameter of RawToken should be the "raw" token, i.e., exactly what appears in the text. The last one is the normalized word. So, you might be right about the `RawToken("will",...)` situation, IF the original text says something else.
- "'s" is indeed ambiguous. I struggled to do something intelligent there. If you have an idea, please let me know!
- Double contractions are not that common, so I am Ok skipping them for simplicity.
- The other cases should all be handled. If they're not, can you please add unit tests?

**Comment by kwalcock** [comment]
The new tests were placed in [TestContractions](https://github.com/clulab/processors/blob/kwalcock/contractions2/main/src/test/scala/org/clulab/processors/TestContractions.scala) rather than TestTokenizer.  If contractions are not expanded because of ambiguity, should "'ve" be changed to "have"?  I'm not aware of other possibilities there.

**Comment by MihaiSurdeanu** [comment]
Yes, "'ve" should be "have".

**Comment by kwalcock** [comment]
Completed by #706
