### ISSUE TITLE
ScienceUtils does not have charset pinned down

### ISSUE THREAD

**Issue by kwalcock** [clulab/processors#375]
This is related to https://github.com/clulab/eidos/pull/806 and likely also to #359.  Code in ScienceUtils, namely
```scala
  private def loadAccents:Set[Char] = {
    val acf = getClass.getClassLoader.getResourceAsStream(ACCENTED_CHARACTERS)
    assert(acf != null, s"Failed to find resource file $ACCENTED_CHARACTERS in the classpath!")
    val reader = new BufferedReader(new InputStreamReader(acf))
```
and
```scala
  private def loadUnicodes:Map[Char, String] = {
    val map = new mutable.HashMap[Char, String]()
    val is = getClass.getClassLoader.getResourceAsStream(UNICODE_TO_ASCII)
    assert(is != null, s"Failed to find resource file $UNICODE_TO_ASCII in the classpath!")
    val reader = new BufferedReader(new InputStreamReader(is))
```
do not have the Charset pinned down and it is left up to the operating system and user to decide.  In this case we made the files and know the encoding, so it should definitely be specified here.
See also https://docs.oracle.com/javase/7/docs/api/java/io/InputStreamReader.html.

**Comment by MihaiSurdeanu** [comment]
@kwalcock: I am happy to fix this. But which Charset should we use?
Thanks!

**Comment by kwalcock** [comment]
Notepad++, which is never wrong, says UTF-8, and this code seems to work:

```scala
      val reader = new BufferedReader(new InputStreamReader(is, StandardCharsets.UTF_8))
```

I notice that the reader in `loadUnicodes` does get closed (unless there is an exception), but the one for `loadAccents` does not.  I will use the case to justify my paranoid programming practices in other code ;-)

**Comment by BeckySharp** [comment]
> Notepad++, which is never wrong

@kwalcock working with you is so much fun :)
