### ISSUE TITLE
Sentence splitter has bug when EOS_FOLLOWEDBY_BULLET

### ISSUE THREAD

**Issue by kwalcock** [clulab/processors#383]
This issue seems to be crashing Eidos when it runs into the bad values in the begin and end positions.  The line https://github.com/clulab/processors/blob/2c68c0c37cf85d9ed06ba294d30c8ba03f547b68/main/src/main/scala/org/clulab/processors/clu/tokenizer/SentenceSplitter.scala#L100

should probably be
```scala
endPositions += beginPositions.last + crt.raw.length
```
because raw is the ArrayBuffer and its length is related to the length of the sentence and not the length of the token.

I'd like to be able to test this with Eidos and a localPublish of processors, so I'm greedily assigning myself.

**Comment by MihaiSurdeanu** [comment]
You are probably right. Thanks!

**Comment by kwalcock** [comment]
It was a bug, but I was wrong about the fix.  PR soon.

**Comment by kwalcock** [comment]
#379 was merged, but processors still needs to be published before more people see crashes.

**Comment by MihaiSurdeanu** [comment]
Should I release?
