### ISSUE TITLE
Release 8.0.2 depends on `processors-models` version that isn't in maven central

### ISSUE THREAD

**Issue by reynoldsm88** [clulab/processors#386]
Using the public release from [Maven central](https://repo1.maven.org/maven2/org/clulab/processors-corenlp_2.12/8.0.2/) depends on `clulab-models:0.0.5` which isn't released on Maven central (see [here](https://mvnrepository.com/artifact/org.clulab/processors-models)).

Importing it into a project results in a build failure as a result of not finding that artifact. One way to resolve this is to add the Clulab repository as a dependency resolver (although I'm not sure if you want people to do that).

**Comment by MihaiSurdeanu** [comment]
@kwalcock : can you please add here the info about the Artifactory repo?

@reynoldsm88 : we store models in our own Artifactory repo because they are too large for maven.

**Comment by reynoldsm88** [comment]
@MihaiSurdeanu no problem, makes sense, thanks. I was going to add it to README but I didn't know if you wanted the whole world to start hitting your repo.

**Comment by kwalcock** [comment]
As you point out, recent versions of processors have a transitive dependency on the models, but the dependencies are housed in different repos.  If I understand correctly, sbt doesn't automatically deal with transitive dependencies in non-standard repositories.  It's necessary to give it a hint with something like the artifactory line below:
```
resolvers ++= Seq(
  "jitpack" at "https://jitpack.io", // com.github.WorldModelers/Ontologies
  "Artifactory" at "http://artifactory.cs.arizona.edu:8081/artifactory/sbt-release" // org.clulab/glove-840b-300d
)
```
I should add to the Eidos documentation that something depending on Eidos will in turn also need to refer to the artifactory entry.

**Comment by kwalcock** [comment]
And yes, I can add some information to processors about it.

**Comment by kwalcock** [comment]
BTW Processors 8.0.2 has a bug in it that is likely to crash Eidos.  Other uses may be OK.  We're working on getting the update published.

**Comment by reynoldsm88** [comment]
Yea, adding the CLUlab Artifactory solved the issue for me. Was just pointing it out because if your missing that resolver it fails a build that uses the sbt defaults.

I can close the issue if you want @kwalcock

**Comment by MihaiSurdeanu** [comment]
Thanks!

**Comment by kwalcock** [comment]
There is something that can probably be added to processors that might help at least Maven find the transitive dependency.  I am testing now.  It might be useful in version 8.0.3.
