### ISSUE TITLE
Reimplement processors server

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/processors#389]
Oh lord of good software development @kwalcock: @BeckySharp suggested we revive our idea of a processors server to simplify debugging. We had such an implementation a while ago. I discontinued it somewhere around version 7 because it was implemented in akka. akka is the wrong tool for this because it is designed for async communication, whereas this server is meant to have simple synchronous communication. Maybe a simple REST API is better/simpler?

What do you all think?

**Comment by kwalcock** [comment]
I saw this and added it to my list.  Spreading execution across machines usually complicates debugging in my experience.

**Comment by MihaiSurdeanu** [comment]
Let’s discuss tomorrow.

On May 4, 2020 at 10:23:37 AM, Keith Alcock (notifications@github.com)
wrote:

I saw this and added it to my list. Spreading execution across machines
usually complicates debugging in my experience.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/clulab/processors/issues/389#issuecomment-623595807>,
or unsubscribe

**Comment by kwalcock** [comment]
@MihaiSurdeanu, based on recent email exchanges, I plan to close this issue.
