### ISSUE TITLE
MetalNER input format for prediction

### ISSUE THREAD

**Issue by vikas95** [clulab/processors#405]
Hi,

The input sentence to a METAL NER model is an AnnotatedSentence datastructure. 
https://github.com/clulab/processors/blob/1be17b146f49fae0ea6f809e23e4f697d42e8b73/main/src/main/scala/org/clulab/dynet/Metal.scala#L419

I just wanted to make sure that passing empty values for posTags and neTags ( https://github.com/clulab/processors/blob/1be17b146f49fae0ea6f809e23e4f697d42e8b73/main/src/main/scala/org/clulab/dynet/RowReaders.scala#L12 ) will not effect prediction of MetalNER in anyway ?

Second question is where exactly are the tokens converted to their index values before feeding it to the model for NER.

Attaching @kwalcock to make sure I have asked correct questions.

**Comment by MihaiSurdeanu** [comment]
Yes, the NER model does *not* use POS tags and, obviously, NE tags. So, it's Ok to leave them empty.
 The word-to-index conversion happens internally, so you don't need to worry about that.

**Comment by vikas95** [comment]
Cool, thanks for the clarifications.
Closing the issue.
