### ISSUE TITLE
DyNet crashes on this NER task

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/processors#429]
@kwalcock: @gcgbarbosa reports that the DyNet NER crashes when trained on the attached file. The crash does not seem to happen in the same place all the time...

@gcgbarbosa: can you please paste the cmd line you used for training here?

@kwalcock: can you please see if you can replicate this first?
Thank you both!

[train-bottom-bottom-NER.conll.txt](https://github.com/clulab/processors/files/5380537/train-bottom-bottom-NER.conll.txt)

**Comment by kwalcock** [comment]
Please also include the versions or branches of github repos and perhaps operating system and version, options like amount of Java memory, and that kind of thing.  A whole lot can go wrong.  core dumps, stack traces, java error files. and logs all help.

**Comment by kwalcock** [comment]
@gcgbarbosa, did this problem go away?  I haven't yet seen the command line or any other details that would help me investigate.

**Comment by gcgbarbosa** [comment]
Hi @kwalcock, I wish the problem had disappeared, but no. I am just overwhelmed with other things. I will come back to this either by the end of the evening or tomorrow morning. Sorry about the delay.

**Comment by kwalcock** [comment]
No problem.  I can delay a long, long time.

**Comment by gcgbarbosa** [comment]
This is the config file I am using:

```
mtl {
  maxEpochs = 50
  epochPatience = 5
  numberOfTasks = 1

  layers {
    initial {
      learnedWordEmbeddingSize = 128
      charEmbeddingSize = 32
      charRnnStateSize = 16
      c2i = "org/clulab/c2i-en.txt"
    }

    intermediate1 {
      rnnStateSize = 128
      useHighwayConnections = true
      numLayers = 1    }  }

  task1 {
    name = "En NER"
    train = "/work/gcgbarbosa/repos/research/data/train-bottom-bottom-NER.conll"
    dev = "/work/gcgbarbosa/repos/research/data/dev-NER.conll"
    test = "/work/gcgbarbosa/repos/research/data/test-NER.conll"
    type = "basic"

    layers {
      final {
        inference = "viterbi"
      }
    }
  }
}
```

Along with:

```
sbt 'runMain org.clulab.dynet.Metal -conf mtl-proteins.conf -train mtl-proteins'
```

I am using the default settings for the rest.

I am also running it again with the updated master branch so that I can give you the stack trace I was getting with the most updated version of the codebase.

I am running it on `river`.

**Comment by gcgbarbosa** [comment]
And the stack trace:

[stack-trace.txt](https://github.com/clulab/processors/files/5397962/stack-trace.txt)

**Comment by kwalcock** [comment]
I can at least verify seeing the same result on river.  I have it running locally where I hope to be able to catch the exception in the act.

**Comment by kwalcock** [comment]
So far it has refused to crash locally, but it is spitting out more errors than it is making progress.  I'll pick a different random number pretty soon.

```
21:20:21.418 [main] INFO  org.clulab.dynet.SafeTrainer - Caught an invalid gradient exception: Magnitude of gradient is bad: -nan(ind). Reset gradient L2 norm to: 0.0
```

**Comment by kwalcock** [comment]
This is just luck, probably, but the program ended with this.  Would any of the output be useful?
```
22:17:11.567 [main] DEBUG org.clulab.dynet.Metal - Started evaluation on the development dataset for task 1 (En NER)...
22:23:44.918 [main] INFO  org.clulab.dynet.Metal - Accuracy on 11595 development sentences for task 1 (En NER): 56.36
22:23:44.918 [main] INFO  org.clulab.dynet.Metal - Precision on 11595 development sentences for task 1 (En NER): 8.32
22:23:44.918 [main] INFO  org.clulab.dynet.Metal - Recall on 11595 development sentences for task 1 (En NER): 84.05
22:23:44.918 [main] INFO  org.clulab.dynet.Metal - Micro F1 on 11595 development sentences for task 1 (En NER): 15.14
22:23:44.918 [main] INFO  org.clulab.dynet.Metal - 	P/R/F1 for label B-Gene_or_gene_product (18428): 87.87 / 83.34 / 85.54
22:23:44.918 [main] INFO  org.clulab.dynet.Metal - 	P/R/F1 for label I-Gene_or_gene_product (1275): 0.66 / 94.27 / 1.31
22:23:44.918 [main] INFO  org.clulab.dynet.Metal - 	P/R/F1 for label * (19703): 8.32 / 84.05 / 15.14
22:23:44.918 [main] INFO  org.clulab.dynet.Metal - Average accuracy across 1 tasks in epoch 9: 56.36
22:23:44.918 [main] INFO  org.clulab.dynet.Metal - Average P/R/F1 across 1 tasks in epoch 9: 8.32 / 84.05 / 15.14
22:23:44.918 [main] INFO  org.clulab.dynet.Metal - Best epoch so far is epoch 4 with an average F1 of 99.5, and average accuracy of 99.95.
22:23:44.918 [main] INFO  org.clulab.dynet.Metal - Epoch patience is at 0.
Disconnected from the target VM, address: '127.0.0.1:65156', transport: 'socket'

Process finished with exit code 0
```

**Comment by MihaiSurdeanu** [comment]
Hmm... This going to be one of those non-deterministic errors...
I have also seen this error before, but rarely. I wonder if there is a way to prepare for whenever we see this error again, to understand better where it crashes in the C code?

**Comment by kwalcock** [comment]
It looks like all the output appears in mtl-proteins-epochN.* and task1.dev.output.N files, which I've saved.  I'll pick a different random number and try again.

**Comment by MihaiSurdeanu** [comment]
Yeah, I don't think that's consistent, so repetition would be nice.

But the stack trace looks similar all the time.

**Comment by kwalcock** [comment]
It's something in the trainer and I'll look, but it would also be great to catch it in the act, write a unit test, know that it's fixed, etc.
```
[error]         at edu.cmu.dynet.internal.Trainer.update(Trainer.java:39)
```

**Comment by kwalcock** [comment]
My computer is not cooperating in this attempt at failing, but it looks like amy has gdb installed, so I will try there in the meantime.

**Comment by kwalcock** [comment]
It ran to completion again on my computer, but it did crash on amy and I am able to catch the SIGSEGV signal.  The *.so file used in fatdynet has been stripped of symbols, so it can't tell me much, but I can change that.  SEGV hints at a pointer problem rather than a problem with the math and pointers are hard to track down.

I notice that clab/dynet has been updated quite a bit recently and it is now passing unit tests again.  A merge results in quite a few conflicts that I have to study carefully.  At least one of the updates is a patch for a memory leak in the CUDA version which probably helps us.  They have worked on C# and Rust bindings a lot which to me indicates an extended life of the project.

**Comment by MihaiSurdeanu** [comment]
1. I agree that keeping the .so files debuggable is worth it, even if it produces a larger library.
2. Great point about merging the latest dynet! I knew I forgot something at the WM meeting today: I wanted to ask about the same thing... Thank you! Maybe after solving the conflicts we can raise a PR with your changes?

**Comment by kwalcock** [comment]
It isn't feasible to not strip the symbols.  The file is 160MB without and can't be used with github.  I have to publish a debug version of fatdynet locally.

**Comment by kwalcock** [comment]
It never happens when someone is looking.  The program ran to completion on amy while being monitored by the debugger.  It lived for over four hours.  Maybe next time.

**Comment by MihaiSurdeanu** [comment]
This is going to be hard...
Thank for trying!

**Comment by kwalcock** [comment]
I did not get back to this on Wednesday.  If @gcgbarbosa needs an answer before I find one, he can try another run.  So far 3/4 of mine have worked.  One thing extra I do is `export _JAVA_OPTIONS=-Xmx16g`.  Perhaps that has been helping.  I will try again soon.

**Comment by kwalcock** [comment]
I am looking into exceptions just now because of a different crash.  I will try to get something out of fatdynet better than "unknown exception".  However, this RuntimeException should be catchable in Processors.  I suspect there are exception conditions in dynet that can never be completely avoided.  Metal.train might be revised to catch the exception and do something like stop and use the previous best answer, move on to the next epoch, start over with a different random seed, at least end the training cleanly, etc.

```
[error] (run-main-0) java.lang.RuntimeException: unknown exception
[error] java.lang.RuntimeException: unknown exception
[error]         at edu.cmu.dynet.internal.dynet_swigJNI.Trainer_update(Native Method)
[error]         at edu.cmu.dynet.internal.Trainer.update(Trainer.java:39)
[error]         at edu.cmu.dynet.Trainer.update(Trainer.scala:5)
[error]         at org.clulab.dynet.SafeTrainer.update(SafeTrainer.scala:16)
[error]         at org.clulab.dynet.Metal.batchBackprop(Metal.scala:247)
[error]         at org.clulab.dynet.Metal.$anonfun$train$3(Metal.scala:169)
[error]         at org.clulab.dynet.Metal.$anonfun$train$3$adapted(Metal.scala:136)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:929)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:929)
[error]         at org.clulab.dynet.SentenceIterator.foreach(TaskManager.scala:128)
[error]         at org.clulab.dynet.Metal.$anonfun$train$2(Metal.scala:136)
[error]         at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:12)
[error]         at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
[error]         at scala.collection.immutable.Range.foreach(Range.scala:156)
[error]         at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
[error]         at org.clulab.dynet.Metal.train(Metal.scala:124)
[error]         at org.clulab.dynet.Metal$.main(Metal.scala:423)
[error]         at org.clulab.dynet.Metal.main(Metal.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error] Nonzero exit code: 1
```

**Comment by MihaiSurdeanu** [comment]
Thanks @kwalcock !

I'll try to handle this one better.

**Comment by kwalcock** [comment]
I've got the error handling largely revised so that fewer problems from C++ should map onto unknown exception and more should show their messages.

**Comment by kwalcock** [comment]
I'm not sure this will make a difference, but two bug fixes just went into DyNet which I ran into while in the test portion of an example program looking for memory leaks: https://github.com/clab/dynet/pull/1627 and https://github.com/clab/dynet/pull/1593.

**Comment by MihaiSurdeanu** [comment]
Thank you Keith!!

**Comment by MihaiSurdeanu** [comment]
This crash no longer happens. Confirmed by @gcgbarbosa.
