### ISSUE TITLE
Caught in the act: Use of ExpressionVector does not guard against premature garbage collection

### ISSUE THREAD

**Issue by kwalcock** [clulab/processors#437]
In Utils.mkCharacterEmbedding, the code that simplifies down to this
```scala
    val fwOuts = transduce(charEmbeddings, charFwRnnBuilder)
    val fwOut = fwOuts.last
   ...
    val bwOuts = transduce(charEmbeddings.reverse, charBwRnnBuilder)
    val bwOut = bwOuts.last
   ...
    concatenate(fwOut, bwOut)
  }
```
makes two ExpressionVectors, then only uses the last of the Expressions for concatenation.  After last(), the ExpressionVectors are free to be garbage collected, and they are.  Unfortunately, the C++ code that eventually deletes the vector also deletes all of the contained Expressions, not knowing that the last one is still being used.  By the time concatenate() gets called, the Expression is often gone (it depends on the asynchronous garbage collection and perhaps on whether C++ has reappropriated the memory yet).  This results in a SIGSEGV error.  I've verified that this is happening to specific pointers to the underlying memory.

This is very much related to a comment in the Scala code:
```scala
class Expression private[dynet](
  private[dynet] val expr: internal.Expression,
  // Expressions sometimes rely on things (e.g. wrapped C++ vectors) that get deleted when the JVM
  // garbage collector runs. By explicitly grabbing references to them, we can prevent this
  // premature garbage collection.
  val references: Seq[AnyRef] = Seq.empty
) {
```

The strategy doesn't work in this situation.  I believe the work-around is to skip the ExpressionVector in this case and just use a Scala Seq of Expressions from which the last can be plucked.  This might not be the only instance of the problem, but other times transduce is called, the resulting ExpressionVector is not available for garbage collection until after concatenation.

This is all happening suspiciously close the the code below and I wonder if it may be a false fix:
```
    // Some embeddings may be empty in some weird Unicode encodings
    ...
    val fwOut =
      if (fwOuts.nonEmpty) fwOuts.last
      else transduce(Array(lookup(charLookupParameters, 0)), charFwRnnBuilder).head // 0 = UNK

```

**Comment by MihaiSurdeanu** [comment]
Very nice find!
So, what fix do you suggest exactly? I am not sure changing from an ExpressionVector to a Seq[Expression] would work, since the ExpressionVector is implemented as a collection also? Am I wrong?

**Comment by kwalcock** [comment]
It *seems* to be working.  The Seq stays in Scalaland and does not garbage collect its elements that are referenced elsewhere.  So far the Expressions are staying around.  The ExpressionVector wraps a C++ vector<dynet::Expression> which does delete its elements.   I could also just add a line after concatenate that does something with fwOuts and bwOuts to force them to stay around, but it would just be busy work.

**Comment by MihaiSurdeanu** [comment]
Cool! Should I go through my code to look for these situations?
Also, what is the preferred way to convert the ExpressionVector to Seq[Expression]?

**Comment by kwalcock** [comment]
I'm still testing.  It seems that ExpressionVectors are OK as long as the contained expressions are used before the vector is garbage collected.  It may be just this one problematic case in which last() is extracted and lives on slightly longer than the vector.  I'll be checking each use.

**Comment by MihaiSurdeanu** [comment]
Everything that is generated in the EmbeddingLayer will live for a long time. So there might be more situations like that. I'll check tonight.

**Comment by kwalcock** [comment]
It has crashed again under different & strange circumstances.

**Comment by kwalcock** [comment]
That long life seems to be true.  I don't see that the majority of Scala Expressions are ever garbage collected.  One test run finally crashed after 15,504,951 were created and not destroyed.  Their C++ counterparts are very likely already deleted and I will check on that.  I don't know what is keeping the others around.  They should all be invalid after the ComputationGraph is updated to the next generation.  I think that matches the general observation that memory use creeps up over time and performance goes down as garbage collection is a struggle.

**Comment by MihaiSurdeanu** [comment]
So, the C++ expression seqs are over collected, while the Scala ones are never collected? :)
Clearly both these are major problems. But I don't understand the latter. Why would they not be collected? They should lose their references once their CG is destroyed.

**Comment by BeckySharp** [comment]
Is this a common issue with scala/java/C++ bindings?

**Comment by kwalcock** [comment]
I still have to look into both issues.  The Expressions are not registered with the Scala ComputationGraph at all, unlike with the C++.  Remember in the Scala that there is only ever one graph (per thread) and the association is implicit.  Scala doesn't know to delete the Expressions when the CG moves on (that I have noticed so far).  I'm not really sure yet why they stay around at all.  Maybe it is indeed a JNI thing.  In the meantime I don't trust it to be done right and given how much we're starting to rely on DyNet, am compelled to double check on a few things even when this is already taking forever.

**Comment by MihaiSurdeanu** [comment]
Thanks for doing this Keith! This is important, so take your time.

**Comment by kwalcock** [comment]
It still crashes,  but my counts were off.  I had neglected one static keyword and missed an implicit copy constructor.  Still looking...

**Comment by kwalcock** [comment]
The way to go about handling the memory in an ExpressionVector might be to just change `ExpressionVector.apply(idx: Int): Expression` from
```scala
override def apply(idx: Int): Expression = new Expression(vector.get(idx))
```
to either
```scala
override def apply(idx: Int): Expression = new Expression(vector.get(idx), Seq(vector))
```
or
```scala
override def apply(idx: Int): Expression = new Expression(vector.get(idx), Seq(this))
```
so that the vector or this has to live at least as long as the resulting Expresssion.  That would keep it from being garbage collection out from under the Scala wrapper, at least theoretically.

**Comment by MihaiSurdeanu** [comment]
I see. That would be very nice, as it doesn't impact any of our code.

Also, I think my email with suggestions of getting rid of ExpressionVector was overkill. Even if we want to reduce its usage, we only need to worry about situations where the ExpressionVector "dies" before one of its elements. That is not common in our code (but it does happen).

**Comment by kwalcock** [comment]
There are parts of the code in which conversion is taking place, so that even if ExpressionVector is never cited (in an import or as a variable type), they are still being used.
```scala
def concatenate(exprs: Expression*): Expression = concatenate(new ExpressionVector(exprs))

object ExpressionVector {
  implicit def Seq2ExpressionVector(x: Seq[Expression]) =
    new ExpressionVector(x)
}
```
One or more gotchas (and maybe a bug) are still getting us, but it doesn't seem like the solution can be too far away.

**Comment by BeckySharp** [comment]
exciting progress guys!

**Comment by MihaiSurdeanu** [comment]
By guys you should mean Keith 👍

**Comment by BeckySharp** [comment]
well, yes for sure he's the one solving it, but you BOTH can share in the
celebration of the progress!!!

**Comment by MihaiSurdeanu** [comment]
I am the fan watching an exciting sports event and cheering for my team :)

**Comment by BeckySharp** [comment]
hahahahaha YES that!

**Comment by MihaiSurdeanu** [comment]
I am not sure how the Scala compiler optimizes things, but, in this code:
```
override def apply(idx: Int): Expression = new Expression(vector.get(idx), Seq(this))
```
it might be possible that the there is a *new* Seq(this) created on every call to apply. That is clearly excessive...

**Comment by MihaiSurdeanu** [comment]
I take it back. It should create a new Seq on every call to apply, and have it stored in `references`, which was designed exactly for that purpose. Please ignore the last two messages :)

**Comment by kwalcock** [comment]
IIRC late last week I ran the unit tests of Eidos using that potential fix and it passed once.  However, I had not yet checked whether the memory was ever freed correctly or whether it worked with processors, especially under stress.

**Comment by MihaiSurdeanu** [comment]
This is exciting!

**Comment by kwalcock** [comment]
One test program survived overnight, which it hasn't done for a long time, using the code
```scala
  override def apply(idx: Int): Expression = new Expression(vector.get(idx), Seq(vector))
```
There's more testing to do (other test programs and especially other operating systems), but it's a very good sign, I think.  The overhead is troublesome, but given that every single Scala Expression involves this extra Seq, adding the ExpressionVector to the list will probably not be very noticeable.

**Comment by MihaiSurdeanu** [comment]
Yay!!! Awesome progress!

**Comment by kwalcock** [comment]
Two machines worked all night without a crash, one running a processors test program and the other running Eidos, which processed over 10,000 files.  So far, so good.

I think that DyNetSync can be moved to FatDynet and become standard procedure for anything manipulating a ComputationGraph.  In most cases it will be the only place in which ComputationGraph.renew() needs to be called and it can check to make sure that constraint is not violated.  In the meantime it has assertions so that a single process doesn't reenter the synchronized section which has helped catch the unexpected out of order operations (lazy variables, class initialization, exception handling).  I need to update it work when we really do want parallel processing, which might happen fairly soon if the serial version continues to be stable.

**Comment by MihaiSurdeanu** [comment]
Yay!!

I agree with all suggested changes.

**Comment by kwalcock** [comment]
Eidos on the one machine read the 45,000 document corpus in three days or so without crashing once.  I restarted the program twice, but just because I hadn't transferred all the files in one batch.  Memory use would go both up and down as garbage collection cycles ran and I've seen ExpressionVectors being finalized.  I'm pretty satisfied with this version.  All four layers (dynet, fatdynet, processors, eidos) are locally published, so I'm preparing updates for all of them.

On the AWS machine the processors test program has been running.  It has never crashed in C++ code or crashed otherwise, but the oom_reaper (out of memory) did kill the process twice.  I'm not sure how successfully the -Xmx kind of setting is getting from the environment variable, through sbt, to Java, and to what extent it is heeded.  I have read that the garbage collector may have difficulty managing memory needs because it can't take into account what C++ is doing.  There may be some garbage collector settings that can help with the issue, like a high water mark, that should be tuned.  I'll look into those when the full stack is ready to deploy there.

So, it's good news mostly and maybe the ordeal is soon over.

**Comment by MihaiSurdeanu** [comment]
Wow! Big achievement!

**Comment by MihaiSurdeanu** [comment]
I now think that the solution to create a Seq on each call to `ExpressionVector.apply()` is probably overkill... This means that every time one access an element of the ExpressionVector, we create a different Seq? That sounds like too much...
Instead I would propose to add a new field to the ExpressionVector class that parallels the `private[dynet] val vector: internal.ExpressionVector`. That is:
1. add `private scalaVector: Vector[Expression]` as a new member to the `ExpressionVector` class.
2. Make sure that any method in the `ExpressionVector` class that changes the original `vector` also changes the additional `scalaVector` in the same way.

This way, we do not create a new `Seq` on any access, but a single one for each `ExpressionVector`, which to me seems better. What do you think?

**Comment by kwalcock** [comment]
I should see how many times that code is being called to make sure it's an issue.

If it's fair to change DyNet code, then I'd start with what seems more like the problem: Expression,
```scala
class Expression private[dynet](
  private[dynet] val expr: internal.Expression,
  // Expressions sometimes rely on things (e.g. wrapped C++ vectors) that get deleted when the JVM
  // garbage collector runs. By explicitly grabbing references to them, we can prevent this
  // premature garbage collection.
  val references: Seq[AnyRef] = Seq.empty
)
``` 
I'm not sure there's a good reason that references is a `Seq`.  It looks like there are plenty to times in which a Seq is constructed just to hold one item.  If it was
```scala
val reference: AnyRef
```
then either the one item could be used or in the cases there are more, the same `Seq(item1, item2)` would work is well, one would think.

**Comment by MihaiSurdeanu** [comment]
I think it's fair to change the Scala wrapper.
I agree with the suggested change to Expression.
And I still think the change to ExpressinVector.apply is necessary. Even if we don't currently use it that much, accessing a vector's element should be much more frequent than the creation of that vector.

**Comment by kwalcock** [comment]
If `Expression` is changed, then lots of `Seq(item1)` will be simplified to `item1` including the one in `ExpressionVector`.  Then there shouldn't be a need to cache a `Seq` for the vector so that it can be reused for each element.
```scala
new Expression(vector.get(idx), Seq(vector))
```
might be just
```scala
new Expression(vector.get(idx), vector)
```

**Comment by MihaiSurdeanu** [comment]
I think that is better.
Also, I am not sure my solution is correct, as the ExpressionVector might be discarded before its elements...
Yours might be as good as it gets.

**Comment by kwalcock** [comment]
AFAIK the Scala/Java ExpressionVector can't be discarded (garbage collected) precisely because it is being referred to by its elements... at least until the elements can be discarded as well.

**Comment by MihaiSurdeanu** [comment]
Hey, does your idea below work?

```
new Expression(vector.get(idx), vector)
```

**Comment by kwalcock** [comment]
It passed all the unit tests and didn't crash in the process.  All the Expressions that unnecessarily took a Seq(item) were simplified to just item as well.  I need to do the stress tests with it.    It needs to work on large jobs to make sure garbage collection doesn't cause a problem.

**Comment by MihaiSurdeanu** [comment]
Good news. Thanks!

**Comment by kwalcock** [comment]
I believe to have found that the Scala FloatPointer, IntPointer, and UnsignedPointer were leaking their C++ counterparts.  In some cases, if I can be certain that the Java garbage collector has finished, then I can now inspect the C++ heap and show that it is completely empty.  The C++ cleanup operation has been updated to remove objects that were previously left dangling for the OS to handle.  I'm working through example programs checking for other leaks, building up to processors and eidos.

**Comment by BeckySharp** [comment]
mihai, it’s second christmas! +100 keith!

**Comment by MihaiSurdeanu** [comment]
Wow!

How did you discover this, and how did you fix it?

**Comment by kwalcock** [comment]
This probably could have been discovered with a simple code review, but it was done the hard way with low-level instrumentation calling heap tracking functions.  Googling for things like crtdbg.h, _CrtDumpMemoryLeaks, _CRTDBG_ALLOC_MEM_DF, _CrtSetBreakAlloc should get someone else on track.  Every malloc and new has been rerouted to versions that keep better tabs.  It comes at a performance cost, so there are macros to turn it on and off.  These will eventually be reported to CMU if they hold.

Old code:
```scala
class FloatPointer {
  val floatp = dn.new_floatp
  set(0f)

  def set(value: Float): Unit = dn.floatp_assign(floatp, value)

  def value(): Float = dn.floatp_value(floatp)
}
```
New code:
```scala
class FloatPointer {
  val floatp = dn.new_floatp
  set(0f)

  def set(value: Float): Unit = dn.floatp_assign(floatp, value)

  def value(): Float = dn.floatp_value(floatp)

  override protected def finalize(): Unit = {
    dn.delete_floatp(floatp)
  }
}
```

**Comment by MihaiSurdeanu** [comment]
Oh, so nice!

I wonder how many other Scala classes are affected by the lack of a `finalize` method?

**Comment by kwalcock** [comment]
I'll be checking.  It was probably just luck that a sample program included a `FloatPointer` and it's probably not what's wrong with processors, but that kind of thing might occur elsewhere.

The ParameterCollection has also been leaking and I had addressed/fixed that for the parallel version and am moving it to this debugging version so that it can be verified.  It came up in the next example app that I tested.

**Comment by kwalcock** [comment]
These were addressed in https://github.com/clab/dynet/pull/1629 and https://github.com/clab/dynet/pull/1628 and will soon be available in the master branch of fatdynet.  They are currently still in a side branch, but it seems safe to close this.
