### ISSUE TITLE
nokogiri should be updated

### ISSUE THREAD

**Issue by kwalcock** [clulab/processors#438]
There is a security warning related to nokogiri.  Those with the right permissions can see it at https://github.com/clulab/processors/security/dependabot/docs/Gemfile.lock/nokogiri/open.  The fix is apparently to update to 1.11.0.rc4.  I don't really want to use an rc version, especially since I don't know what it is doing or how to tell if it works.  Others are welcome to test a fix or I can watch for the released version.

**Comment by kwalcock** [comment]
@BeckySharp, this warning might be flagged because of the contents of Gemfile.lock.  You get blamed for that file.  Do you know where it came from or how it is generated and whether it is safe for me to just edit the version numbers in there? It looks like 1.11.0 is available and changing it might help remove this ugly warning (https://github.com/clulab/processors) from the top of our github pages.  lock files might not need to be checked in.  If it was generated from Gemfile, then maybe it's a temporary artifact of some build process that can be .ignored.

**Comment by BeckySharp** [comment]
I like the idea of deleting it -- i have a VERY poor cargo-culty understanding of Gemfiles and all their pizazz... any chance @gcgbarbosa could speak up if deleting it from github (i.e., not tracking it) is good/bad?
Or regardless if we can just update the version and not care?

**Comment by gcgbarbosa** [comment]
In general, lock files should be tracked. They ensure the same version of the libraries is going to be installed and used every time you deploy the documentation. Deleting it might result in unexpected behavior when you compile the documentation. Misbehavior is unlikely to happen though. Very rarely a library is going to change enough to make the application stop working or change the output of the system.

**Comment by BeckySharp** [comment]
Thanks!!! ok, so is the consensus to STILL track the lock file and update
the version to silence the warning?

**Comment by gcgbarbosa** [comment]
Yes, I think we should keep the file.
The two options that come to my mind are:
1. keep the file, change the version to silence the warning and check if the new version does not affect how the documentation looks.
2. delete the file, and periodically check if the documentation changed due to possible library updates.

**Comment by BeckySharp** [comment]
@kwalcock let's go with 1

**Comment by kwalcock** [comment]
OK.  I don't know offhand how to create the documentation from these files.  How the documentation looks probably just involves a diff of all the files.

**Comment by BeckySharp** [comment]
well -- there are instructions for offline docs, if you don't want to
launch them, maybe I can try if you push the change, but IDK when I will
get to that tbh

**Comment by kwalcock** [comment]
Read instructions?  No way!  Where are they, though?  I have no idea how this fits together.  Is it this in the Gemfile?  Step 1: install a different operating system, Step 2: install ruby, Step 3: install gem, Step 4: install jekyll?

**Comment by BeckySharp** [comment]
hahahahahaha
almost
they're here: http://gh.lum.ai/odinson/offline-documentation.html

**Comment by kwalcock** [comment]
Thanks, @BeckySharp and @gcgbarbosa.  It seems to be fixed now.
