### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by xia0nan** [clulab/processors#444]
Hi,

It seems that I cannot connect to **http://artifactory.cs.arizona.edu:8081/artifactory/sbt-release**. Can you help to verify?

Thanks,
Shawn

**Comment by MihaiSurdeanu** [comment]
@kwalcock : can you please check?

**Comment by kwalcock** [comment]
The link seems to be working from a web browser.  We have been having a configuration problem in which addresses have been rewritten with river substituted for artifactory. 
 If you see http://river.cs.arizona.edu:8081/artifactory/sbt-release/org/clulab/metal-loc-ner/1.0.0/metal-loc-ner-1.0.0.jar, then changing it to artifactory.cs.arizona.edu can make it work.  Also, connecting to artifactory from different cs.arizona.edu machines is not working, but it doesn't look like you are doing that.

**Comment by enoriega** [comment]
I confirm I can open http://artifactory.cs.arizona.edu:8081/artifactory/sbt-release

**Comment by kwalcock** [comment]
It looks like the download can be provoked properly from the UI now without the subdomain being changed from artifactory.cs to river.cs.  I'll close this and welcome anyone to reopen if the problem reappears.
