### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by kwalcock** [clulab/processors#461]
The README.md says
```
corenlp - GLP Version
```
but is GPL meant instead?

**Comment by kwalcock** [comment]
I always notice these things right after pressing the button.  Nothing is said about the openie license in the README.md file.  Although other (sub)projects include LICENSE.txt files, there is none for openie.  In addition, the build system only mentions the Apache license, but the individual (sub)projects need to have at least the exceptions to this noted so that they are incorporated into the metadata.

**Comment by MihaiSurdeanu** [comment]
Yes, can you please fix the license typo?
openie is Apache too.
