### ISSUE TITLE
Global case (in)sensitivity

### ISSUE THREAD

**Issue by danebell** [clulab/processors#47]
In an Odin application where case sensitivity doesn't matter, it would be convenient to have some global variable (or at least rule-level variable) to turn off case sensitivity rather than having to enter `(?i)` at the start of every regex. I think this ought to apply to quoted strings, too.

**Comment by myedibleenso** [comment]
There's actually an old discussion about this in a `reach` issue: https://github.com/clulab/reach/issues/11

Do you have something different in mind?

**Comment by danebell** [comment]
Sorry, this is just a duplicate. I forgot that that issue existed and expected to find it in processors.
