### ISSUE TITLE
Inline LexiconNER changes

### ISSUE THREAD

**Issue by enoriega** [clulab/processors#471]
I made a temporary work around to extend the functionality of LexiconNER aux classes in REACH to support the creation of in-memory lexicons, specifically:

https://github.com/clulab/reach/blob/decouple_kb/processors/src/main/scala/org/clulab/processors/sequences/FastInlineLexiconNERBuilder.scala#L10-L23

https://github.com/clulab/reach/blob/decouple_kb/processors/src/main/scala/org/clulab/processors/sequences/InlineLexiconNer.scala

The main "enhancement" was to pass the lexicon as an `Map` instead of sequence of paths to files. @MihaiSurdeanu suggest the method signature should instead receive an iterator that produces the tuples of the map, which could be already in memory or can be produced lazily.

While they work, they most be ported back here in such a way to reduce code duplication.

For context of the changes, please look at: https://github.com/clulab/reach/pull/750

**Comment by MihaiSurdeanu** [comment]
Thanks @enoriega !

@kwalcock: can you please move this functionality into the LexiconNER classes? Maybe as an iterator rather than a prebuilt Map? But that is not that important, since these lexicons are not huge. Thanks!

**Comment by kwalcock** [comment]
I finally saw this and it looks very useful.  So there are three kinds: standard on disk, override on disk, and in memory.  It looks like the in memory version replaces the standard version in this example.  Might it have some other precedence instead?  Should there be a method in which all three are allowed and something to say how the new one relates to the other three, like something for first, middle, or last?

**Comment by MihaiSurdeanu** [comment]
@kwalcock : what do you mean by "override on disk"?

In any case, I think we need to support two functionalities in parallel: load from disk (or resource rather), and load from memory.

**Comment by BeckySharp** [comment]
IDK what mihai thinks, but that sounds like overkill to me, personally

**Comment by enoriega** [comment]
I believe @kwalcock means to the two different formats: The "standard" KB file format and the "NER override" file format.
What I did was an adaptation only to the standard file format, the NER is still being loaded directly from disk

**Comment by kwalcock** [comment]
For "override on disk" I meant an override KB that is in a file/resource.

**Comment by MihaiSurdeanu** [comment]
I see.

I think we should expect either all of them on disk, or all of them in memory.

**Comment by kwalcock** [comment]
It might be done so that you can mix and match.  There are still only two slots, one for standard and one for override, but for each you can choose between memory and file.

**Comment by kwalcock** [comment]
I did start working on this last week.  If the situation or context changes, please let me know.

**Comment by enoriega** [comment]
The circumstances remain the same. I will use these changes on reach when you're done. Thanks!

**Comment by kwalcock** [comment]
I'm not quite sure why `kbs: Map[String, Seq[String]]` but then later this inside information about the order:
```scala
val order = Seq("Gene_or_gene_product", "Family", "Cellular_component", "Simple_chemical", "Site", "BioProcess", "Disease", "Species", "CellLine", "TissueType", "CellType", "Organ")
```
Will starting out with a `Seq[String, Seq[String]]` in which the `Seq` determines the order not work?  I guess that means there could be duplicates, but an assertion can rule that out.

**Comment by enoriega** [comment]
This is a left over of a debug session. I was controlling for the order, but forgot to delete it

**Comment by MihaiSurdeanu** [comment]
Good point.

**Comment by enoriega** [comment]
@kwalcock @MihaiSurdeanu Fixed

**Comment by kwalcock** [comment]
Don't try too hard.  I was replacing/converting/porting the whole thing to processors.

**Comment by kwalcock** [comment]
Reach is using processors 8.2.6.  Should I make the processors changes to that version as well, perhaps bumping it up to 8.2.7 so as not to force reach to update to the current version of processors?

**Comment by enoriega** [comment]
@kwalcock I had to change the signature to receive a Seq instead of a Map to fix a bug introduced by removing that order sequence. I hope this doesn't affect to much the port code you may already had in place

**Comment by kwalcock** [comment]
That was handled in #477, I believe.
