### ISSUE TITLE
"DyNet's computation graph is a static variable, so this block must be synchronized."

### ISSUE THREAD

**Issue by nezda** [clulab/processors#488]
I recently used `CluProcessor` (`v0.3.1` the default: https://github.com/lum-ai/odinson/blob/ac6ca7bb379cd8ab74c88edfa14b9c08e770f8b5/extra/src/main/scala/ai/lum/odinson/extra/AnnotateText.scala#L76) on a modest number of well-behaved documents and noticed the parallelism was absent (next I tried `FastNLPProcessor` and now I know where it got its name). JVisualVM pointed definitively at this clearly known issue: https://github.com/clulab/processors/blob/43b80875cb0539a967090e1771144da95e8f2375/main/src/main/scala/org/clulab/dynet/Layers.scala#L285-L286 . This lock chokes out all parallelism in using that processor within a single-process, multi-threaded application which is a damn shame. Any chance that lock granularity could be loosened to allow independent inputs / documents to be processed independently (e.g., `synchronized(docId.intern()) {...}` is a gross pattern that might work)? Maybe something could become immutable or some state `ThreadLocal`? (I have no idea: this is all currently a black box to me.)

**Comment by kwalcock** [comment]
In the meantime, https://github.com/clab/dynet/issues...

**Comment by kwalcock** [comment]
I haven't completely given up on this idea, but the planned approach did not work despite probably a month or more of effort.  It may be addressed in a different way, possibly using a different library.
