### ISSUE TITLE
Let BioNLPTokenizerPostProcessor mutant detection match Reach rules

### ISSUE THREAD

**Issue by danebell** [clulab/processors#49]
[Reach](http://github.com/clulab/reach) has had its [mutant detection rules](https://github.com/clulab/reach/blob/master/src/main/resources/edu/arizona/sista/reach/biogrammar/modifications/mutants.yml) improved. The [BioNLPTokenizerPostProcessor](https://github.com/clulab/processors/blob/dc8126b5b6a6a3aed98e8b565b0c5f581292778b/src/main/scala/edu/arizona/sista/processors/bionlp/BioNLPTokenizerPostProcessor.scala#L307) should get these or similar improvements, barring unforseen complications.

**Comment by kwalcock** [comment]
The class `BioNLPTokenizerPostProcessor` disappeared with #247.  Perhaps this is something that should be addressed in reach now.  @enoriega, is this still an issue?

**Comment by kwalcock** [comment]
This has been moved to https://github.com/clulab/reach/issues/782.
