### ISSUE TITLE
Undocumented dependency on SVM-rank

### ISSUE THREAD

**Issue by aolney** [clulab/processors#50]
Some tests fail without this dependency. Simply installing SVM-rank binaries to /usr/local/bin solves the problem:

https://www.cs.cornell.edu/people/tj/svm_light/svm_rank.html

**Comment by MihaiSurdeanu** [comment]
Thanks Andrew!

We addressed this issue a while ago, but forgot to document. Please see the new section on External Dependencies in the README.
