### ISSUE TITLE
Group sentences by length?

### ISSUE THREAD

**Issue by kwalcock** [clulab/processors#514]
If the sentences of a document or group of documents were sorted by length, could those of the same length be run through the same computation graph?

It looks like quite a few methods would need to change signatures in order to work with a group of sentences so that the grouping can be propagated all the way down to the metal routines.  Would it be worth it?

**Comment by MihaiSurdeanu** [comment]
I think  this is a great idea. This is a common trick in deep learning to speed up things. 
Before we get into changing method signatures, I wonder what speedup we're looking at here. Would it be possible to run a simple test with a simple dynet model to understand what time we're looking at in cleaning up/recreating the comp graph?

**Comment by kwalcock** [comment]
Here are some further thoughts.  The code modifications for changing just one of the mtl predictions are shown in branch https://github.com/clulab/processors/tree/kwalcock/groupSentences.  They are fairly extensive but manageable.  In running modifications on the very small collection of quite small test documents included in a processors test directory, the following numbers were collected.

Document | Sentence Count | Unique Sentence Lengths | Savings
--: | --: | --: | --:
1 | 19 | 17 | 11%
2 | 13 | 13 | 0%
3 | 20 | 15 | 25%
4 | 13 | 13 | 0%
5 | 13 | 12 | 8%
6 | 11 | 11 | 0%
7 | 10 | 10 | 0%
8 | 12 | 11 | 8%
9 | 13 | 10 | 23%
10 | 1 | 1 | 0%

So, document 1 usually requires 19 computation graphs (per mtl object), 1 for each sentence, but it might make do with 17 because that's how many different sentence lengths there are.  If reusing a computation graph made the operation (forward pass) completely free, which it isn't, and grouping sentences of like length was completely free, which it isn't, then one might save the amount of time in the fourth column.  For documents of these fairly short lengths, the savings seems unlikely to be worth the effort.  However, these ancient test documents are probably significantly smaller than what we usually see so that the chance of duplicate lengths is small.  Also, perhaps extra emphasis should be placed on the worst case, long document, which might have significantly fewer sentence lengths than sentences.  The reading times definitely have a long tail in which a few long documents slow down the time to completion of the entire job.  (Sometimes the documents get sorted by length and read longest first to avoid problems like this.)  It might be that the document style of some corpora favor relatively short sentences with a tighter distribution, especially compared to literary documents like those in https://core.ac.uk/download/pdf/162100435.pdf.  It seems useful to extend the chart above to an actual corpus that has been read with particular attention to large documents.

**Comment by MihaiSurdeanu** [comment]
Thanks!
Yes, seeing data on "real" documents would be nice!
Also, if savings are meaningful, we could pad sentences to increase the number of sentences of same length. For example, we could pad all sentences < 20 tokens such that they become 20 tokens in length.

**Comment by kwalcock** [comment]
I recall that from class.  My first concern was cases where the more quickly calculated answer matches the slower answer exactly.

**Comment by kwalcock** [comment]
If I understand this correctly, the `srlSentence` method (https://github.com/clulab/processors/blob/c0af4ba81249f16d63652af70580211d88b1a7f9/main/src/main/scala/org/clulab/processors/clu/CluProcessor.scala#L282) will run `mtlSrla.predict()` on the very same sentence for each of the predicates of the sentence.  I'm watching the predicates go by and see this many per sentence: 6, 5, 3, 16, 8, 6, 5, 4, 7, 9, 8.  At these quantities I think there would be savings even if different sentences are seldom the same length.  It's probably worth it for the single sentences already.  I almost have code complete to run all the mtl parts on groups of sentences, but it would be fairly easy to test just this part independently.

**Comment by kwalcock** [comment]
This code in that same srlSentence method is very strange:
```scala
      val headPositions = new ArrayBuffer[Int]()
      val pred = predicateIndexes(pi)
      for(i <- words.indices) {
        headPositions += pred
      }
```
it seems to boil down to this, which is just an array of the very same redundant number:
```scala
val headPositions = Array.fill(words.length)(predicateIndexes(pi)) 
```
Is that the intent?

**Comment by MihaiSurdeanu** [comment]
Yes that was my intent :)

**Comment by kwalcock** [comment]
In the branch kwalcock/groupSentences (https://github.com/clulab/processors/tree/kwalcock/groupSentences), CluProcessors, Metal, and Layers are revised to work on multiple sentences at a time if they are the same length.  They also to the multiple predicates at a time for the same sentences.  The number of AnnotatedSentences being processed by mtlSrla.predict is nearly 7 (6.96 when zeros are not counted).  Nevertheless, it doesn't have any effect on performance.  It seems like dynet is not able to take advantage of the situation and I don't yet know why.  Perhaps something in Layers is unnecessarily updating values that haven't changed so that calculations are repeated anyway.

Stage | Grouped Time | Ungrouped Time
--- | --: | --:
chunking | 0:00:00:00.000 | 0:00:00:00.000
clear | 0:00:00:00.000 | 0:00:00:00.000
discourse | 0:00:00:00.000 | 0:00:00:00.000
group | 0:00:00:00.009 | 0:00:00:00.011
lemmatize | 0:00:00:00.988 | 0:00:00:01.129
parse | 0:00:01:07.905 | 0:00:01:07.274
recognizeNamedEntities | 0:00:00:34.185 | 0:00:00:34.004
resolveCoreference | 0:00:00:00.000 | 0:00:00:00.000
srl | 0:00:03:43.483 | 0:00:03:40.369
tagPartsOfSpeech | 0:00:00:34.357 | 0:00:00:34.668
totals | 6.02 minutes | 5.96 minutes

**Comment by MihaiSurdeanu** [comment]
Hmm. I'll take a look soon.

**Comment by MihaiSurdeanu** [comment]
I went through your branch carefully, and I think the code is correct.
My only explanation now is that the `ComputationGraph.renew()` call is indeed cheap. Cheaper than the overhead added to sort and group the sentences. But this seems to disagree with the savings numbers you have in this thread... Any ideas of where the differences come from?
