### ISSUE TITLE
New release incorporating changes from #519?

### ISSUE THREAD

**Issue by adarshp** [clulab/processors#520]
Hi @kwalcock , would it be possible to make a new release of `processors` so that we can use the changes introduced in #519 in [`clulab/tomcat-text`](https://github.com/clulab/tomcat-text)?

**Comment by kwalcock** [comment]
Yes, unless @MihaiSurdeanu knows of a reason why not.

**Comment by MihaiSurdeanu** [comment]
Ok to release!

**Comment by kwalcock** [comment]
v8.4.2 has been sent to maven central.  It should be available soon.

**Comment by adarshp** [comment]
Thanks @kwalcock !
