### ISSUE TITLE
Confusion about heads of graphs

### ISSUE THREAD

**Issue by kwalcock** [clulab/processors#522]
In [srlSentence](https://github.com/clulab/processors/blob/c05ef7fa10b5303fc564f0fa929ee1581117bee1/main/src/main/scala/org/clulab/processors/clu/CluProcessor.scala#L282) of CluProcessors there's a line `roots ++= predicateIndexes` and afterwards, the edges are calculated.  There is an example sentence in which the `predicateIndexes` are 1, 5, 6 and the edges are
```
1 -> 0
5 -> 4
6 -> 7
6 -> 5
```
Is 5 still supposed to be a root?  Maybe it is a predicate, but it is also the destination of an edge.  If it is a root, it messes up Eidos serialization because the roots aren't tracked separately and it otherwise looks like it's in the middle of a something, the source of an edge.  We wouldn't know that it's a root unless perhaps all sources were roots.

@MihaiSurdeanu, can you clarify the semantics?

**Comment by MihaiSurdeanu** [comment]
Good find @kwalcock !
No, in this example 5 is not supposed to be a root. Roots are nodes that never appear on the right hand side of these edges.

**Comment by kwalcock** [comment]
A PR is on the way.  It sure seems like roots = edges.sources -- edges.destinations, which could be calculated in the constructor (or provided optionally) rather than passed to it.  I'll avoid changing the interface, though.

**Comment by kwalcock** [comment]
See #523.  However, there may be an additional problem.

**Comment by MihaiSurdeanu** [comment]
I merged that PR. What additional problem?

**Comment by kwalcock** [comment]
Now I'm not sure where I wrote it down.  In DirectedGraphIndex.toDirectedGraph, the old roots shouldn't be used with the new edges.  I added a check in the DirectedGraph constructor and several things are creating directed graphs that don't fit this definition of roots.
```
  {
    val sources = edges.map(_.source).toSet
    val destinations = edges.map(_.destination).toSet
    val actualRoots = sources -- destinations

    if (actualRoots != roots)
      println("It went wrong!")
  }
```

**Comment by MihaiSurdeanu** [comment]
I think I remember seeing this in some syntactic trees as well.
I think we should be lenient and adjust the actual roots in the created DG
to be correct ones.

**Comment by kwalcock** [comment]
Regarding my comment above, I've got an open window from yesterday where I had written it down and will press the comment button.

If the roots need to be double checked each time anyway, should they just be removed from the DirectedGraph case class constructor?  I'm not sure whose code that would break.  I've turned them into a var and am replacing them with the calculated value to see what breaks or fixes.

**Comment by MihaiSurdeanu** [comment]
Fair point. I think they can be calculated on the fly, which should make
the constructor more robust.

**Comment by kwalcock** [comment]
So far, fixing it in DirectedGraphIndex has solved the problems in Eidos.  It looks like DirectedGraphIndex.removeEdge and addEdge are being called without either of them updating the roots.  I should probably change those so that the class is consistent.  The DirectedGraph could probably stay the same then unless performance should be sacrificed for the correctness guarantee.  I can't judge that well.

**Comment by MihaiSurdeanu** [comment]
Thanks! And good catches!


On July 7, 2021 at 7:40:38 PM, Keith Alcock ***@***.***)
wrote:

So far, fixing it in DirectedGraphIndex has solved the problems in Eidos.
It looks like DirectedGraphIndex.removeEdge and addEdge are being called
without either of them updating the roots. I should probably change those
so that the class is consistent. The DirectedGraph could probably stay the
same then unless performance should be sacrificed for the correctness
guarantee. I can't judge that well.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/clulab/processors/issues/522#issuecomment-875757449>,
or unsubscribe

**Comment by kwalcock** [comment]
The code above, in which a root cannot be a destination of an edge, does not especially address loops.  In one test document so far, FastNLPProcessor.parseWithStanford produces an edge 6 -> 6 with root of 6 for a GraphMap.UNIVERSAL_ENHANCED.  Luckily, this one isn't causing a problem with Eidos.  Now I observe other files are turning up additional loops.  One has a graph which no edges, but one root of 0.  I've made some minimal changes in a PR and am making sure that they at least solve the Eidos problem.  It doesn't unnecessarily "correct" these other situations.

**Comment by MihaiSurdeanu** [comment]
Thanks!

Note that cycles are legal for both SRL and syntactic dependencies...

**Comment by kwalcock** [comment]
Can the cycles still include a root?

**Comment by MihaiSurdeanu** [comment]
Yes...

**Comment by kwalcock** [comment]
For srlSentence at least, "Roots are nodes that never appear on the right hand side of these edges."  In a loop, all nodes appear on the right hand side.  A cycle cannot include a root then.

The problem with Eidos is that roots are not serialized, so they need to be recalculated.  That doesn't seem possible.  Maybe the serialization needs to be changed.  The compositional grounding makes use of the roots and they need to be preserved across serialization somehow.  Maybe it can be cleared up at the meeting today.

**Comment by kwalcock** [comment]
Does a root have to be a source of an edge?  Some code above says that it does:
```scala
val actualRoots = sources -- destinations
```
but there are places in the code where it isn't the case.  In a sentence with one word and no edges, is there a root, for instance?

**Comment by MihaiSurdeanu** [comment]
It needs to be either a source, or to be a standalone node that is not part of any edge.

**Comment by kwalcock** [comment]
Hopefully last question: are all standalone nodes roots or just some of them?

**Comment by MihaiSurdeanu** [comment]
Standalone nodes have to be roots because they are not reachable otherwise.
