### ISSUE TITLE
measurements not recognized

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/processors#525]
Hi @marcovzla,
These tests fail in the branch numeric_processor because numbers are not recognized correctly:
https://github.com/clulab/processors/blob/numeric-processor/main/src/test/scala/org/clulab/numeric/TestNumericEntityRecognition.scala#L132-L135

Can you please take a look? I'd like to merge this in master this week, if possible.
Thanks!

**Comment by marcovzla** [comment]
It should be fixed now

**Comment by MihaiSurdeanu** [comment]
Thanks!
