### ISSUE TITLE
"one hundred thousand" not recognized

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/processors#530]
It seems the number grammar requires that a number sequence start with digits. That is, this is recognized `100 thousand`, but this is not `one hundred thousand`.

@marcovzla, can you please look a this?

**Comment by MihaiSurdeanu** [comment]
A different problem, but on the same topic: `100,000 ha` is not recognized, because of the comma in the number.

**Comment by marcovzla** [comment]
I fixed the issue with the commas in #532 

I couldn't replicate the issue with `one hundred thousand`.
I added it as a test in #532. The test passes locally.

**Comment by marcovzla** [comment]
Nevermind, I think I see the issue.

**Comment by marcovzla** [comment]
Issue was fixed in #532
