### ISSUE TITLE
Documentation of WordEmbeddings

### ISSUE THREAD

**Issue by BeckySharp** [clulab/processors#538]
There should be some documentation on how to use the Word Embeddings (instantiate, apply, etc)

**Comment by kwalcock** [comment]
...including lists of published versions of glove.

**Comment by BeckySharp** [comment]
also... was `mostSimilarWords` intentionally not kept in the trait?

**Comment by BeckySharp** [comment]
specifically, this is included:
https://github.com/clulab/processors/blob/master/main/src/main/scala/org/clulab/embeddings/SanitizedWordEmbeddingMap.scala#L22

But ExplicitWordEmbeddingMap doesn't have the `mostSimilarWords` method, which I use (and is generally useful).  The old one is only in the test suite, so I will use this deprecated one for now, but FYI

**Comment by BeckySharp** [comment]
and...

this (these) shouldn't be private, right?: 

https://github.com/clulab/processors/blob/master/main/src/main/scala/org/clulab/embeddings/SanitizedWordEmbeddingMap.scala#L408

**Comment by BeckySharp** [comment]
https://xkcd.com/1172/
![image](https://user-images.githubusercontent.com/5384073/128610453-2dccff3b-1dae-40a7-b6fc-5c99b2405123.png)

**Comment by MihaiSurdeanu** [comment]
The `loadMatrix` methods are called from the c'tor, so they should not be exposed.
`mostSimilarWords` might be useful to have.

**Comment by BeckySharp** [comment]
as far as I can tell, there is no way to construct the versions with
mostsimilarwords

**Comment by kwalcock** [comment]
@BeckySharp, your wish is my command, eventually, like after it is long too late.  This has been addressed in #714.  May others benefit.
