### ISSUE TITLE
Ran into Error when Running the Script 'test-ner.sh'

### ISSUE THREAD

**Issue by ZhengTang1120** [clulab/processors#551]
[info] Loading settings for project processors-build from plugins.sbt ...
[info] Loading project definition from /net/kate/storage/work/zhengtang/processors/project
[info] Loading settings for project root from release.sbt,compile.sbt,test.sbt,version.sbt,publish.sbt,build.sbt ...
[info] Loading settings for project openie from build.sbt ...
[info] Loading settings for project corenlp from build.sbt ...
[info] Loading settings for project main from test.sbt,build.sbt ...
[info] Set current project to root (in build file:/net/kate/storage/work/zhengtang/processors/)
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] Running org.clulab.dynet.Metal -test mtl-ner-epoch2 -conf org/clulab/mtl-en-ner.conf
Using the following properties:
	conf = org/clulab/mtl-en-ner.conf
	test = mtl-ner-epoch2
15:44:40.253 [run-main-0] DEBUG org.clulab.dynet.Utils - Initializing DyNet...
[dynet] Loading DyNet from /tmp/libdynet_swig-6023491855555698466.so...
[dynet] random seed: 2522620396
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
15:44:40.593 [run-main-0] DEBUG org.clulab.dynet.Utils - DyNet initialization complete.
15:44:40.659 [run-main-0] DEBUG org.clulab.dynet.TaskManager - Reading task 1 (En NER)...
15:44:41.067 [run-main-0] DEBUG org.clulab.dynet.TaskManager - ============ starting task 1 ============
15:44:41.068 [run-main-0] DEBUG org.clulab.dynet.TaskManager - Read 14987 training sentences for task 1, with shard size 1499.
15:44:41.068 [run-main-0] DEBUG org.clulab.dynet.TaskManager - Read 3466 development sentences for task 1.
15:44:41.068 [run-main-0] DEBUG org.clulab.dynet.TaskManager - Read 3684 testing sentences for task 1.
15:44:41.068 [run-main-0] DEBUG org.clulab.dynet.TaskManager - Using taskWeight = 1.0
15:44:41.068 [run-main-0] DEBUG org.clulab.dynet.TaskManager - Task type = basic.
15:44:41.068 [run-main-0] DEBUG org.clulab.dynet.TaskManager - ============ completed task 1 ============
15:44:41.068 [run-main-0] DEBUG org.clulab.dynet.TaskManager - Read 1 tasks from config file.
15:44:41.078 [run-main-0] DEBUG org.clulab.dynet.Metal - Loading MTL model from mtl-ner-epoch2...
[error] (run-main-0) java.util.NoSuchElementException: next on empty iterator
[error] java.util.NoSuchElementException: next on empty iterator
[error] 	at scala.collection.Iterator$$anon$2.next(Iterator.scala:41)
[error] 	at scala.collection.Iterator$$anon$2.next(Iterator.scala:39)
[error] 	at scala.collection.mutable.FlatHashTable$$anon$1.next(FlatHashTable.scala:217)
[error] 	at scala.collection.IterableLike.head(IterableLike.scala:109)
[error] 	at scala.collection.IterableLike.head$(IterableLike.scala:108)
[error] 	at scala.collection.AbstractIterable.head(Iterable.scala:56)
[error] 	at org.clulab.dynet.Utils$ByLineStringBuilder.build(Utils.scala:805)
[error] 	at org.clulab.dynet.Utils$ByLineStringBuilder.build(Utils.scala:794)
[error] 	at org.clulab.dynet.Utils$ByLineBuilder.build(Utils.scala:657)
[error] 	at org.clulab.dynet.ViterbiForwardLayer$.load(ViterbiForwardLayer.scala:113)
[error] 	at org.clulab.dynet.ForwardLayer$.load(ForwardLayer.scala:135)
[error] 	at org.clulab.dynet.Layers$.loadX2i(Layers.scala:194)
[error] 	at org.clulab.dynet.Metal$.$anonfun$load$2(Metal.scala:399)
[error] 	at org.clulab.dynet.Metal$.$anonfun$load$2$adapted(Metal.scala:398)
[error] 	at scala.collection.immutable.Range.foreach(Range.scala:158)
[error] 	at org.clulab.dynet.Metal$.$anonfun$load$1(Metal.scala:398)
[error] 	at org.clulab.utils.Serializer$.using(Serializer.scala:12)
[error] 	at org.clulab.dynet.Metal$.load(Metal.scala:394)
[error] 	at org.clulab.dynet.Metal$.apply(Metal.scala:418)
[error] 	at org.clulab.dynet.Metal$.main(Metal.scala:453)
[error] 	at org.clulab.dynet.Metal.main(Metal.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] Nonzero exit code: 1
[error] (Compile / runMain) Nonzero exit code: 1
[error] Total time: 17 s, completed Sep 13, 2021 3:44:41 PM

**Comment by MihaiSurdeanu** [comment]
Fixed in PR #553
