### ISSUE TITLE
Expose comments in the LexiconNER, so they are visible to other code

### ISSUE THREAD

**Issue by kwalcock** [clulab/processors#569]
Currently, code in `StandardKbSource` removes the comments before further processing: https://github.com/clulab/processors/blob/c8dfa85975eea9f6452220b407a4630940d550f1/main/src/main/scala/org/clulab/sequences/LexiconNERBuilder.scala#L87.
Other code like that in `UnitNormalizer`, https://github.com/clulab/processors/blob/c8dfa85975eea9f6452220b407a4630940d550f1/main/src/main/scala/org/clulab/numeric/UnitNormalizer.scala#L12-L26 , actually rereads the same file.
That's a little wasteful at runtime, but it does keep things concerned with comments and those unconcerned nicely separated during development.

There are at least three strategies to deal with this:
1. Generalize the code in `UnitNormalizer` to take arguments to specify the file/resource and go ahead and process it twice when called for.
2. Subclass StandardKbSource and have it make use of the comments, perhaps routing them to some user-supplied function that can handle them as needed.  This might necessitate calling one of the `LexiconNER` constructors that takes a `StandardKBSource` like https://github.com/clulab/processors/blob/c8dfa85975eea9f6452220b407a4630940d550f1/main/src/main/scala/org/clulab/sequences/LexiconNER.scala#L157-L162.  To get to that, code interested in the comments might have to duplicate some code in the many other apply methods.  The overhead is only incurred when something is interested.
3. Include some extra parameter in the apply methods that indicates whether the comments should be saved (or just go ahead if their existence implies that they should be).  Store the comments in a way similar to how the tokens are stored.  This is complicated, because the tokens can be stored in tries and the keys have their cases altered.  There might need to be one kind of trie for tokens with comments and a different kind without so that not every trie node gets multiplied in size.  They would probably change from a Boolean to a (Boolean, Option[String]) or Option[Any] in case the comments are later processed into some kind of object.  It might be that the comments for different files are formatted differently so that one parameter does not suffice to describe the desired behavior.

It seems like there is a reasonable probability that the contents of the comments changes and that the code to parse and store them will need to change.  That and the invasiveness of option 3 leads me to disfavor it right now.  I think that we should start with option 1 in the short term and then if it goes well, like if hiding things in comments turns out to be a successful strategy, promote it to option 2.  If needed, there would be multiple functions or subclasses to account for the kinds of information stored in the comments.

That's my initial take on it, at least.

**Comment by kwalcock** [comment]
FYI @EgoLaparra, @MihaiSurdeanu

**Comment by MihaiSurdeanu** [comment]
I agree. I think option 1 is the pragmatic choice.
Thanks Keith!

**Comment by kwalcock** [comment]
This was handled with #570.
