### ISSUE TITLE
version 5.8.5 not available on Maven Central

### ISSUE THREAD

**Issue by nicolopignarocket** [clulab/processors#57]
If you [search for this library](http://search.maven.org/#search%7Cga%7C1%7Corg.clulab%20processors_2.11) in Maven Central, the latest pushed release is 5.8.4.
In the README installation instructions, though, 5.8.5 is used as current version.

Could you please push 5.8.5 to Maven Central as well?

**Comment by MihaiSurdeanu** [comment]
Sorry, this is my fault. I updated the version number too soon.
Please use 5.8.4 for now. I need to add a few more things to 5.8.5 before release.
