### ISSUE TITLE
Make seasons configurable

### ISSUE THREAD

**Issue by kwalcock** [clulab/processors#572]
A NumericEntityRecognizer can be passed optionally into the CluProcessor constructor.  If passed, it will replace a default NumericEntityRecognizer in
```scala
  lazy val numericEntityRecognizer: NumericEntityRecognizer =
      numericEntityRecognizerOpt.getOrElse(NumericEntityRecognizer())
```
The default one uses a resource "org/clulab/numeric/SEASON.tsv" and we'd like to be able to configure this.  It seems that there should only be one NumER and it has multiple kbs of which this resource will be one.  It shouldn't be separated into its own "thing" so that there are multiple, specialized NumERs.

It seems to me that NumericEntityRecognizer.mkLexiconNer needs to take an argument for this resource (perhaps forwarded by the apply method), one that defaults to the standard tsv file, so that it can be slipped into the constructor call for the LexiconNER, like this:

```scala
  // this matches essential dictionaries such as month names
  def mkLexiconNer(customSeasons: String = "org/clulab/numeric/SEASON.tsv"): LexiconNER = {
    val kbs = Seq(
      "org/clulab/numeric/MONTH.tsv",
      "org/clulab/numeric/MEASUREMENT-UNIT.tsv",
      customSeasons
    )
    val isLocal = kbs.forall(new File(resourceDir, _).exists)
    LexiconNER(
      kbs,
      Seq(
        false, // false = case sensitive matching
        true,
        true
      ),
      baseDirOpt = if (isLocal) Some(resourceDir) else None
    )
  }
```
The question might be how the string gets that far and there are unfortunately two options:

One is to pass the same optional customSeasons String with a default value to the CluProcessor constructor and have it, assuming there is no numericEntityRecognizerOpt, use the string to construct the (almost) default one.  This is a messy kind of a double optional in which one is dependent on the other, but it is easy for the caller.

The other is to use the customSeasons String to construct the desired NumericEntityRecognizer in advance and then pass it as the numericEntityRecognizerOpt.  This is slightly more work for the caller, but it seems cleaner.

Mihai wanted the first option.  I'm double checking and making sure I understand it correctly.

**Comment by MihaiSurdeanu** [comment]
@kwalcock : I'll let you decide on this. I can leave with either one :)

**Comment by kwalcock** [comment]
If the optional, custom resource is specified with the CluProcessor and if there is already a numericEntityRecognizerOpt specified, we would not try to somehow edit that NumER so that it used the custom resource.  This would be an error.  What we really want is either a numericEntityRecognizer or a customSeasons, but that is about as difficult to do as the second option in which the customSeason is used to create the numericEntityRecognizer.  For the first option there is an effective

```scala
require(numericEntityRecognizerOpt.isEmpty || customSeasonsOpt.isEmpty)
```

**Comment by kwalcock** [comment]
It is looking more complicated.  There is a SeasonNormalizer that wants to use the same SEASON.tsv file that the default NumericEntityRecognizer does.  If the latter is customized with a different seasons file, I assume that the SeasonNormalizer should take it into account.  Unfortunately the SeasonNormalizer isn't even a class.  It is a (companion) object.  It is initialized on demand and cannot take any arguments for the constructor.  There is not a good way to pass information at runtime from the NumericEntityRecognizer to the SeasonNormalizer.  A global, mutable variable is a possibility, but that is a last resort.

The SeasonNormalizer is used from mentions.package.scala (unfortunately one of the strange package objects) which calls SeasonNormalizer.norm() and SeasonNormalizer.adjustYearRange().  This is a package object calling a method on a companion object.  Methods in the package IIRC are dynamically loaded and called by Odin based on rules with actions like

```
- name: date-range-1
  priority: ${rulepriority}
  label: DateRange
  type: token
  example: "It took place between 12 May 2000 and 12 June 2020"
  action: mkDateRangeMention
  pattern: |
    /(?i)between/ @date1:Date /(?i)(and|to)/ @date2:Date
```

It looks like the NumericEntityRecognizer creates the Odin ExtractorEngine that will invoke the actions.  Perhaps that can be a custom ExtractorEngine that has a little inside information so that the SeasonNormalizer can be called in a way that uses the correct tsv file...

**Comment by MihaiSurdeanu** [comment]
Agreed.

Maybe the SeasonNormalizer can be made a class, and added as a field in NumericEntityRecognizer, so your option 2 still holds?

**Comment by kwalcock** [comment]
Thanks for the hint!  If SeasonNormalizer can be a class, then I have a plan, convoluted, but a plan.

**Comment by kwalcock** [comment]
The NumericEntityRecognizer is supposed to be reloadable.  It looks like the reload was intended to account for changes made in the rules, but not changes made to the lexiconNER or the actions, even though both of these are influenced by the contents of files that might need to be reloaded.  @MihaiSurdeanu, is it OK to leave it this way?  The SEASON.tsv ends up affecting both the lexiconNER and also the actions via the SeasonNormalizer that uses the comments in the file.  It gets complicated and is probably not even necessary.

**Comment by MihaiSurdeanu** [comment]
It's fine for now. Thanks for checking!
(The key info to debug are the rules. As long as those are reloadable, I'm Ok)

**Comment by kwalcock** [comment]
Part of the discussion above is a little off the mark because the main constructor for CluProcessor is protected.  The simplified, public version does not have the numericEntityRecognizerOpt.  I've used a seasonPathOpt there and am converting it into the numericEntityRecognizerOpt for the call to the protected version.
