### ISSUE TITLE
NER stop list not stopping words which are not entirely lowercased

### ISSUE THREAD

**Issue by hickst** [clulab/processors#58]
NER stop list is missing words which are first-letter-uppercase (a problem) and all caps (probably *not* a problem).

**Comment by hickst** [comment]
In discussion, I think we agreed that:
* We currently have only a very small number of stop words and we should be conservative about adding to the stop list; adding only critical conflicting words.
* The current stop words have an overwhelming probability of being non-entities anyway.
We could, therefore, allow stopping lowercase and initial capital words without missing too much.

**Comment by MihaiSurdeanu** [comment]
Solved.
