### ISSUE TITLE
Incorrect parsing for words with a hyphen

### ISSUE THREAD

**Issue by endovitskayaV** [clulab/processors#602]
mention.characterStartOffset is always = 4, and there is no text before the hyphen in the found text.
Example:
rules:
  - name: ner-cancer
    label: CANCER
    priority: 1
    type: token
    pattern: |
      (/(?i)^breast$/ | /(?i)^non-visceral$/) carcinoma
      

texts:                                                                  mentions: 
"some text non-breast carcinoma"             ->   characterStartOffset = 4, characterEndOffset = 30, text = "breast carcinoma"
"some text breast carcinoma"                     ->   characterStartOffset = 4, characterEndOffset = 26, text = "breast carcinoma"
 "some long text non-visceral carcinoma"  ->   not found
 
 Maybe a hyphen should be escaped? I tried using \ or ``, but it did not help.
 Note: no problem for version 6.3.0

**Comment by MihaiSurdeanu** [comment]
Hi,
I am not sure I can replicate this issue. Can you please attach the code + grammar you used for this?

Also, maybe it is relevant here: some of the within-word dashes are stripped from the tokens we generate for some prefixes such as "non". This is why "non-breast" will show up as two tokens to Odin: "non", "breast". This is on purpose: this way grammars that operate at token level can leverage these prefixes in the grammar. You can recover the original text when you need from `Sentence.raw`: https://github.com/clulab/processors/blob/master/main/src/main/scala/org/clulab/processors/Sentence.scala#L15
