### ISSUE TITLE
Performance should stay approximately even

### ISSUE THREAD

**Issue by kwalcock** [clulab/processors#604]
This is an example run of version 8.4.8, the previously numbered master:

Stage | Time | Nanoseconds | Proportion
-- | -- | -- | --
chunking | 0:00:00:00.000 | 161700 | 0.00%
clear | 0:00:00:00.000 | 52000 | 0.00%
discourse | 0:00:00:00.000 | 61400 | 0.00%
lemmatize | 0:00:00:00.750 | 750296800 | 0.19%
parse | 0:00:01:17.153 | 77153648600 | 19.24%
recognizeNamedEntities | 0:00:00:42.699 | 42699050800 | 10.65%
resolveCoreference | 0:00:00:00.000 | 165700 | 0.00%
srl | 0:00:04:02.015 | 242015799800 | 60.36%
tagPartsOfSpeech | 0:00:00:37.211 | 37211673200 | 9.28%
  |   |   |  
processing 10 files | 0:00:06:40.945 | 400945577900 | 100.00%

**Comment by kwalcock** [comment]
Here's one for the current master, which might soon be 8.4.9:

Stage | Time | Nanoseconds | Proportion
-- | -- | -- | --
chunking | 0:00:00:00.000 | 168800 | 0.00%
clear | 0:00:00:00.000 | 59400 | 0.00%
discourse | 0:00:00:00.000 | 77200 | 0.00%
lemmatize | 0:00:00:00.347 | 347660700 | 0.08%
parse | 0:00:01:41.668 | 101668399500 | 23.82%
recognizeNamedEntities | 0:00:00:41.526 | 41526004400 | 9.73%
resolveCoreference | 0:00:00:00.000 | 180400 | 0.00%
srl | 0:00:04:03.163 | 243163447900 | 56.98%
tagPartsOfSpeech | 0:00:00:39.007 | 39007275000 | 9.14%
  |   |   |  
processing 10 files | 0:00:07:06.766 | 426766478600 | 100.00%

**Comment by MihaiSurdeanu** [comment]
Thanks @kwalcock !
This aligns well with what I thought.

**Comment by kwalcock** [comment]
If those times aren't unreasonable, then I should go ahead and publish the 8.4.9 that you wanted.

**Comment by MihaiSurdeanu** [comment]
Do you remember what the `parse` times were on that older version where we observed it to be slow?
Also, maybe hang on for a couple of days. I hope to squeeze in one more improvement.

**Comment by kwalcock** [comment]
There are too many older versions for me.

**Comment by MihaiSurdeanu** [comment]
You had an issue a while ago (that I can't find) where you reported this exact same table.

**Comment by kwalcock** [comment]
If something can be tracked down in the GitHub repo, though, I can certainly add the same timing code on the same files.  Around June 11, 2021 there were some other timing tests, but they look very slow.

**Comment by MihaiSurdeanu** [comment]
Do you have a link to those tests?

**Comment by kwalcock** [comment]
GitHub is not doing a very complete search.  Here are some more but they don't look like the same test.

https://github.com/clulab/processors/pull/473
https://github.com/clulab/processors/issues/514

**Comment by kwalcock** [comment]
Also #501.  These are the right columns, but the measurements are about three times as long.

**Comment by MihaiSurdeanu** [comment]
Indeed. Thanks!
Further evidence that the current master is on a good track.

**Comment by MihaiSurdeanu** [comment]
Thanks!

It was #473. If you scroll down, you had similar stats, except the parser
took 4:39. Much slower.
