### ISSUE TITLE
SRL method seems to be renamed...

### ISSUE THREAD

**Issue by BeckySharp** [clulab/processors#608]
to `proc.srl(doc)` 

if I'm right, the docs should be updated (from `labelSemanticRoles(doc)`)

**Comment by BeckySharp** [comment]
also, is it just me or is there no clear link from the docs _back_ to the github page?

.... and if you care.....

i guess because of this:
https://github.com/clulab/processors/blob/master/main/src/main/scala/org/clulab/processors/clu/CluProcessor.scala#L168

you can't (I think?) call the annotation pipeline methods one-by-one on a pre-made Document the way it's listed in the docs -- i.e., if you wanted to make a partial annotation

if you try, you get: 
```
java.lang.RuntimeException: ERROR: Const embeddings not set!
	at org.clulab.processors.clu.CluProcessor.basicSanityCheck(CluProcessor.scala:655)
	at org.clulab.processors.clu.CluProcessor.tagPartsOfSpeech(CluProcessor.scala:430)
	at com.lexmachina.nlp.CluSyntaxAnnotator.mkPartialAnnotation(CluSyntaxAnnotator.scala:44)
...
```

Don't you LOVE it when people mix issues in a single thread!!! :heart:

**Comment by MihaiSurdeanu** [comment]
Thanks @BeckySharp !
I will adjust the documentation soon.

Also, @kwalcock: I think we should not offer a default implementation of `annotate()` in the `Processor` trait, since the implementations for the various processors have diverged. What do you think?

**Comment by MihaiSurdeanu** [comment]
I fixed the documentation:
- Added link back to the github in the first sentence on the landing page.
- Adjusted the description of `annotate` to indicate that it applies just to CoreNLP processors.
- Fixed some other older text that is no longer valid.

@kwalcock : can you please take a look at the doc, to see if I missed something that is no longer valid?

**Comment by kwalcock** [comment]
Correct, @BeckySharp, the CluProcessor needs a `GivenConstEmbeddingsAttachment(doc).perform {` before one can pick and choose pipeline methods.  At one point I had an alternate implementation in which an extra argument was passed around.  We might have also used an implicit argument.  The required order of the pipeline methods may also need to differ.  I will suggest a note to check with the annotate method of the Processor being used for details.

**Comment by kwalcock** [comment]
#610 should be taking care of these things.
