### ISSUE TITLE
Java 17

### ISSUE THREAD

**Issue by kwalcock** [clulab/processors#612]
According to reliable sources, it may require in the call to Java

--add-opens java.base/sun.net.[www.protocol.jar](http://www.protocol.jar/)=ALL-UNNAMED

See https://docs.oracle.com/en/java/javase/16/migrate/migrating-jdk-8-later-jdk-releases.html

This command may help diagnose problems related to missing classes:

mvn dependency:build-classpath

**Comment by kwalcock** [comment]
To add new Scala code but still work in Maven, one might need things like this:
```xml
              <plugin>
                <groupId>net.alchim31.maven</groupId>
                <artifactId>scala-maven-plugin</artifactId>
                <version>4.6.1</version>
                <executions>
                    <execution>
                        <id>scala-compile-first</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>add-source</goal>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>scala-test-compile</id>
                        <phase>process-test-resources</phase>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <scalaVersion>2.12.15</scalaVersion>
                </configuration>
            </plugin>

```

```xml
        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <version>2.12.15</version>
        </dependency>
        <dependency>
            <groupId>org.clulab</groupId>
            <artifactId>processors-main_2.12</artifactId>
            <version>8.4.8</version>
        </dependency>
    ...
    <repositories>
        <repository>
            <id>artifactory.cs.arizona</id>
            <url>http://artifactory.cs.arizona.edu:8081/artifactory/sbt-release</url>
        </repository>
    </repositories>
```

**Comment by MihaiSurdeanu** [comment]
Nice @kwalcock !

Should we add a sample pom.xml file somewhere in the documentation?

**Comment by kwalcock** [comment]
This issue is here mostly to preserve Becky's findings after Slack forgets it and until we advance to more recent Java versions.  If I understand it correctly, the XML above is mostly helpful for people wanting to add a few Scala source files to their otherwise Java project built with Maven.  It isn't directly related to processors.  We usually work the other way around with a Scala project built with sbt to which a few Java files are added.  I don't think we need to document for others how this is done.  We don't document gradle, either, for example.

**Comment by MihaiSurdeanu** [comment]
Fair enough.

**Comment by kwalcock** [comment]
We now have SSL at https://artifactory.clulab.org.
