### ISSUE TITLE
new time rules

### ISSUE THREAD

**Issue by maxaalexeeva** [clulab/processors#627]
Issue 1:

I am trying to write a rule and an action to extract/update norms for `from February/March to June/July`.
https://github.com/clulab/processors/blob/fcb9c9efe23d38285c5fc3203f6289751739eab9/main/src/main/resources/org/clulab/numeric/date-ranges.yml#L178
Based on some printouts, the rule does not extract any mentions. I have already tried a bunch of things (different ways to get at entities, increasing priority for this rule to use mentions extracted in the same file as building block in this rule, and literally having a rule based on exact words), but I can't get this rule to extract anything. I am not sure what I am missing.

Other changes are in draft pr https://github.com/clulab/processors/pull/626 

Issue 2:
Dates like 2014WS are found as one token. Is there a good way to handle this kind of tokenization issue?

**Comment by MihaiSurdeanu** [comment]
Thanks @maxaalexeeva ! I'll take a look at the rule soon.
Issue2: I think this should be handled through character regex patterns in the simple date grammar.

**Comment by MihaiSurdeanu** [comment]
@maxaalexeeva : can you please include here the full sentence with this example?

**Comment by maxaalexeeva** [comment]
@MihaiSurdeanu `These correspond to the dry season (from February/March to June/July).`

**Comment by MihaiSurdeanu** [comment]
Thanks!

**Comment by maxaalexeeva** [comment]
Issue 1: addressed in https://github.com/clulab/processors/pull/629 
Issue 2: addressed in https://github.com/clulab/processors/pull/637
