### ISSUE TITLE
NumericEntityRecognition hangs

### ISSUE THREAD

**Issue by kwalcock** [clulab/processors#663]
This is being transferred from https://github.com/clulab/habitus/issues/160.  This particular sentence was taken from one of the problematic files and added to a unit test:

Table 2 : Development forecasts for the dry cold season 2020_2021 speculations Dagana Lake Podor Matam Bakel Valley Tomato Onion but Yam Okra others 1,016 960 250 80 150 1,300 50 1,200 50 700 2,300 3,800 225 800 2 150 200 3,691 7,160 3 130 1,480 1,136 2,515 300 130 875 1,050 30 365400 3,775 Total 2487 3,450 8,575 825 19 112 Source : LM 12 / Saed The SSF 2020/2021 campaign is timidly being set up on the entire left bank of the Senegal River with the establishment of nurseries .

**Comment by kwalcock** [comment]
The main problem seems to be this rule in `measurements.yml` that is prohibitively expensive to run on long lists of numbers.  The sentence in the second file that "hangs" is similar to the previous one.  We're probably going to need to worry about the computational complexity of our rules.

Table 2 : Development forecasts for the dry cold season 2020_2021 speculations Dagana Lake Podor Matam Bakel Valley Tomato Onion but Yam Okra others 1,016 960 250 80 150 1,300 50 1,200 50 700 2,300 3,800 225 800 2 150 200 3,691 7,160 3 130 1,480 1,136 2,515 300 130 875 1,050 30 365400 Total 2487 3,450 8,575 3,775 825 19 112 Source : LM 12 / Saed in Matam , NPK and urea needs are estimated , harmonized with the Apov committee , then sent to the DRDR since the end of August .

```
  - name: measurement-3
    label: Measurement
    priority: ${ rulepriority }
    type: token
    action: mkSharedMeasurementMention
    pattern: |
      (@number:Number [!tag = /^NN|LRB/]{0,2} [word = /,|and|to/]*)+ @number:Number @unit:MeasurementUnit
 ```

**Comment by MihaiSurdeanu** [comment]
Thanks @kwalcock !
How long does it take to process this sentence with and without the rule above?

**Comment by kwalcock** [comment]
It has never finished, so I don't know, but probably at least 15 minutes.  In the meantime I have re-written the rule to
```
      (@number:Number ([tag = IN] [tag = CD])? [!tag = /^NN|LRB|CD/]{0,2} [word = /,|and|to/]*)+ @number:Number @unit:MeasurementUnit
```
and tests are running now.  If they pass, I'll explain further.

**Comment by kwalcock** [comment]
They just passed.  It is important to add the CD in [!tag = /^NN|LRB|CD/], I think, because otherwise the @number is likely a CD and then the computer has to figure out which sub-rule (either the @number one or the tag one without CD) to attribute the number to and try all combinations to find the best best one.  It seems to work much better if each sub-rule is mutually exclusive.  With just that change, nothing hangs anymore, but one test in TestNumericEntityRecognition fails:

```
    ensure(sentence = "yield will increase from 3600 in 2000-2009 to 4500 kg ha-1 in 2090-2099", Interval(4, 5), goldEntity="MEASUREMENT", goldNorm="3600.0 kg/ha")
```
I believe some of the rule, particularly the {0,2} is there so that "in 2000-2009" and "in 2090-2099" can be satisfied with the tag rule.  I added that separately with `([tag = IN] [tag = CD])?` for cases in which the year is stated.  There are probably lots of better ways to do that, but here is one possibility.  I will put this in a clean branch with a PR so you and Masha can look.

**Comment by MihaiSurdeanu** [comment]
Nice catch @kwalcock ! 
Please merge. There is probably a cleaner solution for the "in YEAR" problem, but I don't see it now.
Thanks!
