### ISSUE TITLE
Splitting up Odin taxonomy into multiple files?

### ISSUE THREAD

**Issue by adarshp** [clulab/processors#686]
I know that an Odin rule files can import other Odin rule files. Is this possible with taxonomies as well? The motivation here is that we are part of the ASIST DARPA project (https://github.com/clulab/tomcat-text), where certain parts of the taxonomy can change significantly when going from one study to the next. For example, the names of rooms changed from Study 2 --> Study 3: https://github.com/clulab/tomcat-text/blob/06c38c3dc0003d01295eb5c4ff996c6d354e8785/src/main/resources/org/clulab/asist/grammars/taxonomy.yml#L16-L105

It would be nice to be able to keep the Study 2 and Study 3 rooms in their own .yml files and import them conditionally based on the analysis we are trying to perform.

**Comment by MihaiSurdeanu** [comment]
The only solution I know is to create different `master.yml` files in which the rules may be shared, but which have their distinct taxonomies. I don't think we support composing taxonomies from multiple `yml` files. Maybe @myedibleenso knows more?

**Comment by adarshp** [comment]
Got it, we will go with the approach you suggested. Thanks @MihaiSurdeanu !
