### ISSUE TITLE
handling holidays

### ISSUE THREAD

**Issue by maxaalexeeva** [clulab/processors#688]
Hi @kwalcock, 

After the recent pr (https://github.com/clulab/processors/pull/687), there was an issue in the holiday normalizer
https://github.com/clulab/processors/blob/33692f8904872a937c17553c8582387d12da3313/main/src/main/scala/org/clulab/numeric/HolidayNormalizer.scala#L27 the holidayCanonical is no longer a string, it's the NormAndUnitClass, which resulted in a couple of numeric entity tests related to holidays to fail. In my current branch (https://github.com/clulab/processors/commit/efdda45ecd0e8700705b9fb25c39b1132af981e7), I tried to fix that, but this test still fails https://github.com/clulab/processors/blob/bf7e33acf3a7517c887c9d2518875cfa0c5e66f3/main/src/test/scala/org/clulab/numeric/TestNumericEntityRecognition.scala#L204 
Would you please have a look when you have a minute? Thanks!

**Comment by kwalcock** [comment]
Oops.  That wasn't the intention.  I'll be looking in the morning.

**Comment by kwalcock** [comment]
Taken care of in #691
