### ISSUE TITLE
Question: is it possible to extract triples?

### ISSUE THREAD

**Issue by adrianR2** [clulab/processors#69]
Hello,
Is it possible to extract triples, (subject, verb, object)? If so, Is there any example available?
Thank you. Adrian

**Comment by MihaiSurdeanu** [comment]
Yes, this should be trivial. You can modify ProcessorExample for this. Your code should go after this line:

https://github.com/clulab/processors/blob/master/src/main/scala/org/clulab/processors/ProcessorExample.scala#L51

There, you have access to the syntactic dependencies for a given sentence. What you want is to find pairs of dependencies that look like this:

(head = some verb, dependency = nsubj)
(head = same verb, dependency = dobj)

The above two dependencies capture subject and direct object, respectively, for a given verb.
For more complicated patterns, I recommend you take a look at Odin, our information extraction platform. See the manual here: http://arxiv.org/abs/1509.07513
And sample project(s) here: https://github.com/clulab/odin-examples

**Comment by adrianR2** [comment]
Thank you!
