### ISSUE TITLE
Tokenizer is turning family names into conjunctions

### ISSUE THREAD

**Issue by hickst** [clulab/processors#70]
The names of small Protein Family are often the names of the individual proteins separated by a slash (e.g. MEK1/MEK3 or MAPK Erk1/3). Unfortunately, the BioNLPTokenizerPostProcessor transforms this syntax into a conjunction of names (e.g. "MEK1 and MEK3") which are then incorrectly intrepreted as several individual proteins.

**Comment by hickst** [comment]
A failing test which brought this issue to light:
   "B-Raf phosphorylates MEK1 and MEK2 on Ser217 and Ser221"
MEK1 and MEK2 here should be proteins but the conjuction is NER-labeled as a protein family.

**Comment by hickst** [comment]
Here are some of the entries from the NER-Grounding-Override.tsv which include slashes.
EGFR/ERBB	uaz	UAZ-PF-73	Family
MAPK Erk1/3	uaz	UAZ-PF-133	Family
MAPK1/3	uaz	UAZ-PF-133	Family
MAPK1/MAPK3	uaz	UAZ-PF-133	Family
MAPK3/MAPK1	uaz	UAZ-PF-133	Family
MEK1/2	uaz	UAZ-PF-132	Family
MEK1/MEK2	uaz	UAZ-PF-132	Family
NRG1/2	uaz	UAZ-PF-151	Family
NRG3/4	uaz	UAZ-PF-152	Family
p160/SRC	uaz	UAZ-PF-144	Family
TCF/LEF	uaz	UAZ-PF-224	Family

**Comment by MihaiSurdeanu** [comment]
@hickst: this is now fixed and pushed in the ner-override branch (together with a few other tokenization errors). If you'd like to adjust the KBs used by the tokenizer, adjust org.clulab.processors.bionlp.ner.KBLoader.TOKENIZATION_KBS.

I added unit tests. All tests pass.
