### ISSUE TITLE
The webapp messes up the project in IntelliJ

### ISSUE THREAD

**Issue by kwalcock** [clulab/processors#711]
It may be that the webapp can't live in the same project.

**Comment by MihaiSurdeanu** [comment]
what is the issue in IntelliJ?

**Comment by kwalcock** [comment]
It's looking like it might not be IntelliJ.  There is an incompatibility between the scalatest and scalatestplus-play libraries that sbt doesn't check because aggregation is turned off.  IntelliJ ignores the aggregation setting and starts complaining.  I have to fix the library versions.

**Comment by kwalcock** [comment]
Addressed in #712
