### ISSUE TITLE
Amino acid abbreviations not being parsed as nouns

### ISSUE THREAD

**Issue by hickst** [clulab/processors#77]
Two amino acid abbreviations (out of 20) clash with words: 'his' is parsed as a possessive pronoun and 'pro' as a foreign word. This means that they do not get recognized as entities and just 'disappear' from many sentences. Can anything be done about this?

**Comment by MihaiSurdeanu** [comment]
Can you please use it in a sentence? :)

Please add examples for both. Can we use capitalization, or other hints there?
