### ISSUE TITLE
Unscallable and extremely slow performance compared to stanford-corenlp

### ISSUE THREAD

**Issue by hsyed** [clulab/processors#8]
I am using an actor based pipeline to annotate 3.2 gb of text in 3 - 4 million text entities. when I use core-nlp directly everything works fine. when I replace that with sistanlp it barely does anything. I am using 12 actors on my macbook to do the work, so 12 instances of annotators.

1. Only one core is saturated.
2. Works barely happens even with the single core.

I suspect some really bad concurrency choices were made. It is probably the interning symbol table.

**Comment by matanster** [comment]
@hsyed care to share the relevant code?

**Comment by scalame** [comment]
was this issue ever resolved?

**Comment by MihaiSurdeanu** [comment]
I was not able to replicate this behavior. My runtimes are comparable to CoreNLP.
Mihai

**Comment by MihaiSurdeanu** [comment]
Closing for now, because we can't replicate it. We can reopen if needed.
