### ISSUE TITLE
Serialize/deserialize Mentions to/from json

### ISSUE THREAD

**Issue by myedibleenso** [clulab/processors#89]
We really need to add support to write/read mentions to/from json.

**Comment by hickst** [comment]
This would be great but I'd like to see it for Reach BioMentions, too.

**Comment by myedibleenso** [comment]
>This would be great but I'd like to see it for Reach BioMentions, too.

Yes!  That's what I really need for my current work, but I think we sure start with pure Mentions.

In another project I have some code to serialize/deserialize Mentions:

https://github.com/myedibleenso/processors-server/blob/master/src/main/scala/processors/api/Mention.scala

https://github.com/myedibleenso/processors-server/blob/fba17bb8888eafd660d32416533334cb16bb572f/src/main/scala/processors/ConverterUtils.scala#L102-L187

Not sure if we'd want to do the same or something similar here...

**Comment by myedibleenso** [comment]
My latest headache is the assembly corpus.  With all of the changes (hopefully improvements) to reach, I've lost the ability to recover a number of annotations.  

If I were just producing a Mention rather than trying to find a mention that corresponds to a particular annotation, it wouldn't be an issue at all...

**Comment by MihaiSurdeanu** [comment]
I agree.
