### ISSUE TITLE
Retrain the NN parser using both WSJ and GENIA

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/processors#97]

**Comment by MihaiSurdeanu** [comment]
- split WSJ and GENIA into train/test
- test CoreNLP (as implemented in FastNLPProcessor) on WSJ and GENIA test. report scores (P/R/F1 for labeled/unlabeled dependencies) separately. 
- train a vanilla model JUST on WSJ. should replicate the results in CoreNLP. 
- train N models with N copies of GENIA appended to WSJ (where N ranges from 1 to 5). Evaluate each on WSJ and GENIA, as above. Goal: performance similar on WSJ, and much better on GENIA.
- With @myedibleenso and @MihaiSurdeanu: integrate the new model in processors (BioNLPProcessor).

**Comment by MihaiSurdeanu** [comment]
- please add instructions on how to train the parser to the Wiki

**Comment by MihaiSurdeanu** [comment]
@terroni: please send us a timeline of expected completion for each step.

**Comment by terroni** [comment]
Week of:
- Nov. 7: split WSJ and GENIA into train/dev/test (finished); test CoreNLP (as implemented in FastNLPProcessor) on WSJ and GENIA test. report scores (P/R/F1 for labeled/unlabeled dependencies) separately.
- Nov. 14: train a vanilla model JUST on WSJ. should replicate the results in CoreNLP; train N models with N copies of GENIA appended to WSJ (where N ranges from 1 to 5). Evaluate each on WSJ and GENIA, as above. Goal: performance similar on WSJ, and much better on GENIA.
- Nov. 21: integrate the new model in processors; add instructions on how to train the parser to the Wiki

**Comment by terroni** [comment]
GENIA was already split into train/dev/test (and future_use, which we can just throw in at the end?). I split WSJ based on [this](https://www.aclweb.org/aclwiki/index.php?title=POS_Tagging_(State_of_the_art)), which does train (0-18), dev (19-21), and test (22-24).

**Comment by myedibleenso** [comment]
I think the standard split for parsing tasks using the WSJ was 23 for test, 02-21 for training, and {01, 22, 24} for dev.

**Comment by terroni** [comment]
What about 00?

**Comment by MihaiSurdeanu** [comment]
00 was the first section annotated and is generally regarded as bad
quality. Ok to skip it.

**Comment by cl4yton** [comment]
Gus: number of models have been trained but performed poorly.  Suspect bug in training or evaluation code, currently investigating.

**Comment by MihaiSurdeanu** [comment]
Solved in CluProcessor.
